import { LINKS } from '../data/site.mjs';

const BODY = [
"## What this site is",
"",
"Dressmaker Guide is an independent, fan-made website about **Dressmaker**, the cozy dressmaking simulation game from developers Jonathan Hau-Yoon (elyaradine), Sara Laubscher (sarandipityx) and Ruan Rothmann (raithza), published by Free Lives under the Cozy Lives label.",
"",
"We are not the developers. We are not a publisher, a distributor or a marketing partner. Nobody paid us to write any of this, nobody sent us a review copy, and no developer has seen these pages before you did.",
"",
"We built this site because the useful information about Dressmaker was scattered across a Steam page, a devlog, a Discord and a few news posts. One page that answers \"what is this game, how does it play, and is it worth my evening\" seemed more useful than five pages of speculation.",
"",
"## What we actually do",
"",
"- We read the official sources: the [Steam store page](" + LINKS.steam + "), the [official Steam announcements](" + LINKS.steamNews + "), the [itch.io prototype page](" + LINKS.itch + ") and the [official devlog](" + LINKS.itchDevlog + ").",
"- We play the game. The advice on [how to play](/how-to-play) and the [sewing tips](/sewing-tips) come from time spent at the cutting table, not from reading someone else's summary.",
"- We say when we do not know. The developers have not published per-fabric stats, a customer roster or in-game prices, so where that information is missing we write that it is missing instead of filling the gap with something plausible.",
"- We date our pages. Every page carries a last-updated date. When a price, a spec or a patch changes, the page changes with it.",
"",
"## How to read this site",
"",
"The [homepage](/) is the overview. The [Dressmaker wiki](/wiki) is the reference layer. The [guide pages](/sewing-tips) are the practical layer, and the [patch notes](/patch-notes) page is the historical record.",
"",
"If you only want one piece of advice: the game is real, it launched on **September 21, 2026** at **$14.99**, and there is a free prototype on itch.io that costs you nothing but download time. Start there.",
"",
"## Corrections and contact",
"",
"We get things wrong sometimes, and the fastest fix is an email from someone who noticed. If you spot an error, an outdated price, a broken link or a claim you cannot find a source for, please [tell us](/contact). We would rather correct a page than defend it.",
"",
"## Independence and disclosure",
"",
"- This site is not affiliated with, endorsed by or sponsored by the Dressmaker development team, Cozy Lives, Free Lives, Valve Corporation or itch.io.",
"- \"Dressmaker\" and all related names, artwork, screenshots and logos are the property of their respective owners. We use them for identification, commentary and review.",
"- We do not host, mirror or redistribute the game, its files or its assets. Download links go to the developers' own pages on Steam and itch.io.",
"- If we ever use advertising or affiliate links, they will be labelled, and they will never change what we recommend. See our [disclaimer](/disclaimer) for detail.",
"",
"## About the site name",
"",
"The domain is dressmakerguide.com. It is a guide about the game **Dressmaker**, not about the trade of dressmaking and not about sewing patterns for real garments. If you arrived looking for paper patterns, we are the wrong site and we would rather say so than waste your time.",
].join("\n");

export const page = {
  url: '/about',
  title: 'About Dressmaker Guide: Who Writes This Fan Site',
  description: 'An unofficial fan site for the cozy dressmaking game Dressmaker: who writes it, how we check facts against official sources, and how to correct us.',
  h1: 'About This Site',
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'About', url: '/about' }],
  body: BODY,
};
