import { LINKS } from '../data/site.mjs';

const BODY = [
"The fastest way to reach the person who runs this site is email.",
"",
"## Email",
"",
"**hello@dressmakerguide.com**",
"",
"We read everything. We answer most things within a few days, and we answer corrections faster than anything else because a wrong fact on a guide page costs readers real money or real time.",
"",
"## What to write to us about",
"",
"- **A correction.** A price, a date, a spec or a patch note that is wrong or out of date. If you can, include the page URL and the official source that contradicts us.",
"- **A broken link.** Download links and store links rot faster than anything else on a game site.",
"- **Something you found in the game that we have not covered.** A fabric behaviour worth adding to the [wiki](/wiki), a customer pattern worth writing up on the [customers](/customers) page, or a trick that saved you a bolt of silk.",
"- **A question about the game.** We answer guide questions by email and, when a question comes up repeatedly, we turn it into a section on the [how to play](/how-to-play) or [troubleshooting](/troubleshooting) page.",
"- **A privacy or legal request.** See the [privacy policy](/privacy) for what we can and cannot do.",
"",
"## What we cannot help with",
"",
"- **Game support and refunds.** We are not the developers. Bugs, crashes, lost saves and Steam refunds go to the [official Steam discussions](" + LINKS.steamDiscussions + ") or Steam Support. The developers also run a Discord, linked from the [itch.io page](" + LINKS.itch + ").",
"- **Review copies, sponsorships or paid placements.** We do not accept them. A page on this site cannot be bought.",
"- **Sewing patterns for real garments.** This is a site about a video game called Dressmaker, not about dressmaking as a trade.",
"- **Requests to remove official screenshots.** We link to the developers' own images rather than re-hosting them. If you are a rights holder and want a specific image removed from a page, email us and we will remove it promptly.",
"",
"## Before you write",
"",
"A few things that let us fix issues in one pass instead of three:",
"",
"1. The exact page URL.",
"2. The sentence or number that is wrong.",
"3. A link to the official source - the Steam page, an official announcement, or the itch.io devlog - that shows the correct version.",
"4. Your platform, if the issue is technical.",
"",
"## Response times",
"",
"There is no support team, so please do not expect a reply in minutes. Corrections to factual errors are treated as urgent. Feature requests and suggestions are read, logged, and often turn up on the site later without a reply - that is not you being ignored.",
"",
"> Note: email sent to this address may be kept briefly so we can fix the issue you reported, then deleted. We do not run a newsletter and we will not add you to anything. See the [privacy policy](/privacy).",
].join("\n");

export const page = {
  url: '/contact',
  title: 'Contact Dressmaker Guide: Corrections & Questions',
  description: 'Email the fan site behind dressmakerguide.com with corrections, broken links or guide questions, and see what we cannot help with, such as game support.',
  h1: 'Contact',
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Contact', url: '/contact' }],
  body: BODY,
};
