import { resolveFigures } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const BODY = [
  "> Short answer: Every commission carries a written brief with **named attribute targets** — one official example reads Quality 70, Flowers 60, Cute 30, Romantic 45 — plus an occasion and a budget. Meet them and you gain coin and reputation; ignore the brief and the reaction tells you so. The developers have never published a customer roster or how the star rating is calculated.",
  "",
  "## Quick reference",
  "",
  "| What a brief contains | Where you see it | Example |",
  "| --- | --- | --- |",
  "| The occasion | The customer's note, in the sketchbook | A wedding, a formal evening, everyday wear |",
  "| Their taste | The same note, in their own words | \"Something soft\", \"not too much fuss\" |",
  "| Attribute targets | Sketchbook, Requirements box | Quality 70, Flowers 60, Cute 30, Romantic 45 |",
  "| Commission limits | Fabric shop | Quality 0/80, Formal 0/50, Simple 0/75, Professional 0/50 |",
  "| A budget | Sketchbook, beside the requirements | 800, and roughly 3.85m of fabric |",
  "| Hard rules | Fabric shop, as a constraint line | \"Use only black\" |",
  "",
  "The developers publish no client roster and no preference score, so the rest is your read of the person. New here? Start with the [dressmaker game](/) overview.",
  "",
  "![The sketchbook open on a customer note](@SHOT_sketch@ The sketchbook open on a customer note, with the requirements beside the pattern choices.)",
  "",
  "## Occasion first, taste second",
  "",
  "Build for the occasion and let taste decide the details: print is a choice on a guest's dress and a mistake against a bride. In your window you choose the brief; in a commission, it chooses you.",
  "",
  "::: cards",
  "### The one big day",
  "A wedding or formal event that forgives nothing: best cloth, restrained decoration, a practice run in cheap fabric.",
  "### The dress that has to keep working",
  "Everyday wear, where wearability beats drama.",
  "### The open brief",
  "\"Make me something lovely.\" No plan, so the customer reacts to the dress itself.",
  ":::",
  "",
  "## Reading taste signals",
  "",
  "Customers rarely say what they want precisely, and some of the signals are not words.",
  "",
  "| Signal | What to listen for | What to do |",
  "| --- | --- | --- |",
  "| Colour language | \"Something soft\" against \"something cheerful\" | Attitude, not hue: two different dresses from matching swatches |",
  "| Adjectives | \"Elegant\" against \"fun\" | Restraint means cleaner lines; permission means decorate |",
  "| Hesitation | A customer who goes quiet when you suggest something | A soft no: offer a second option, and never design from a paused suggestion |",
  "| The shop window | Which finished dress they drift toward while they talk | A free focus group, harder to fake than a request |",
  "",
  "## Turning a vague brief into choices",
  "",
  "Find the closest row below and start there.",
  "",
  "> Note: the attribute names below are the game's, taken from the Requirements box it shows you. Turning vague brief language into those attributes is our framework, not official documentation.",
  "",
  "| What the customer says | Silhouette | Fabric | Colour | Trim |",
  "|---|---|---|---|---|",
  "| \"Something like the one in your window\" | Close to the display, simplified | Same family as the display | What they saw, softer | Almost none |",
  "| \"Whatever you think looks best\" | Your plainest flattering shape | Cloth you have sewn before | A colour that suits them | One accent |",
  "| \"It is for a wedding\" | Formal and structured | The best cloth you can cut twice | Quiet beside the couple | Fine lace, no jokes |",
  "| \"I do not want to stand out\" | Familiar, easy to move in | Matte and forgiving | Muted, near what they wear | Detail at the edges |",
  "| \"I love this colour\" (hand on a bolt) | Whatever shows the cloth off | That exact fabric, if affordable | Their pick; build around it | Echoing trim |",
  "",
  "The safe answer is usually the polite one.",
  "",
  "![A customer in the fitting room reading the dress she was handed in](@SHOT_hero@ Hand-in is where the commission is judged.)",
  "",
  "## How the reward loop works",
  "",
  "Hand a finished dress over and you are paid twice: **coin** buys fabric, **reputation** buys the future. The official bullet list says you \"turn in dresses to customers to gain reputation and coin.\"",
  "",
  "| You give | You get | Risk |",
  "| --- | --- | --- |",
  "| A dress that meets the brief | Coin, reputation and a good star rating | Only the fabric you spent |",
  "| A dress that misses the brief | Less coin, and you see it in the reaction | A miss builds no standing |",
  "| A sabotaged dress | The reaction you were fishing for | Costs the standing that unlocks better work |",
  "| A dress sold off the rack | Steady coin, on a brief you chose | Low: nobody is waiting on it |",
  "",
  "Reputation thresholds are unpublished. Off-rack dresses are the steadier half of the economy, with roughly **35 hours** of story commissions besides.",
  "",
  "![A finished dress with the commission completion options](@SHOT_shop@ A finished dress with the completion options: hand it in, keep working, or sell it off the rack.)",
  "",
  "## Playing the sabotage run on purpose",
  "",
  "[The official Steam page](@LINK_steam@) invites you to \"satisfy (or sabotage!)\" the townsfolk. The feedback is a person, not a scoreboard.",
  "",
  "::: steps",
  "1. **Miss the occasion** — send something theatrical to the customer who asked for everyday wear.",
  "2. **Ignore stated taste** — they told you no pink, so every panel is pink.",
  "3. **Clash fabric and trim** — heavy velvet under delicate lace, or lace on lace until it stops reading as a dress.",
  "4. **Decorate past the point of sense** — buttons, bows and appliqué \"wherever you like\" is the official promise, and the freedom that ruins a silhouette.",
  ":::",
  "",
  "> Warning: the joke costs reputation. A sabotaged dress does not build the standing that unlocks better work, so spend it when reputation is not scarce — after the story gives you a cushion.",
  "",
  "## Recovering from a bad commission",
  "",
  "If you have just handed over a disaster, do not restart.",
  "",
  "::: steps",
  "1. **Practise on the cheapest cloth** — remake the dress in fabric nobody will wear; you are training your eye, not producing a garment.",
  "2. **Take the plain commissions** — an easy dress handed in well beats a risky one handed in badly.",
  "3. **Give the miss a second life** — sell it off the rack, so a dress wrong for one brief still earns back part of its fabric.",
  ":::",
  "",
  "Keep the sketchbook entry: a dress that failed on colour and trim usually had a fine silhouette.",
  "",
  "## Frequently asked questions",
  "",
  "### How many customers are in Dressmaker?",
  "",
  "The developers have not published a customer count or any names. The store page promises \"a whole town of people.\"",
  "",
  "### Is there a score or a star rating for a dress?",
  "",
  "Partly. A turn-in gives you **coin and reputation**, and the customer card shows a **star rating** — one official screenshot shows five stars with only one lit. How those stars are worked out has never been published.",
  "",
  "### Do customers remember a bad dress?",
  "",
  "We cannot verify how the town tracks past commissions. Reputation is the standing currency, so a bad turn-in is a slow cost, not a permanent ban.",
  "",
  "### What is the fastest way to build reputation?",
  "",
  "Match the occasion and the stated taste, and turn dresses in often. No shortcut or coin-bought standing has been published.",
  "",
  "## Where to go next",
  "",
  "Start with the [how to play Dressmaker](/how-to-play) walkthrough, then the [Dressmaker sewing tips](/sewing-tips), the [Dressmaker wiki](/wiki) reference tables and the [Dressmaker Steam release date](/release-date).",
].join("\n")
  .split('\n').map((line) => resolveFigures(line)).join('\n')
  .replaceAll('@LINK_steam@', LINKS.steam);

// Same answers as the FAQ section in the body, in the shape the FAQPage schema wants.
const FAQ = [
  ["How many customers are in Dressmaker?", "The developers have not published a customer count or any names, and we will not invent one. The store page promises a whole town of people."],
  ["Is there a score or a star rating for a dress?", "Partly. Turning in a dress gives you coin and reputation, and the customer's name card also shows a star rating - the official screenshots show one card with five stars where only one is lit. What has never been published is how those stars are worked out. The part that is documented is the target: a commission's Requirements box names attributes with numbers, such as Quality 70, Flowers 60, Cute 30, Romantic 45, and the fabric shop shows the same scale as commission limits."],
  ["Do customers remember a bad dress?", "We cannot verify how the town tracks past commissions. What is safe to say is that reputation is the game's standing currency, so a bad turn-in is a slow cost, not a permanent ban."],
  ["What is the fastest way to build reputation?", "Turn in dresses that match the occasion and the stated taste, and turn them in often. No shortcut or coin-bought standing has been published."]
];

export const page = {
  url: '/customers',
  title: "Dressmaker Customer Preferences: How to Read a Brief",
  description: "How Dressmaker customer preferences work: read the occasion and taste in a brief, turn it into real design choices, and sabotage on purpose without regret.",
  h1: 'Dressmaker Customer Preferences',
  eyebrow: "Commission guide",
  lede: "Customer preferences in Dressmaker are not a hidden stat sheet. The developers have published no client roster, no preference score and no table of who wants which lace. What you get is a brief: an occasion, a person with their own taste, and a dress to make.",
  facts: [
    ['What a brief has', "Occasion, taste, budget, targets"],
    ['Targets are numeric', "Quality 70, Flowers 60, Cute 30, Romantic 45"],
    ['Limits too', "Quality 0/80, Formal 0/50, Simple 0/75"],
    ['Hard rules exist', "Some briefs say \"use only black\""],
    ['Reward', "Coin, reputation and a star rating"],
    ['Second income', "Off-rack dresses in the shop window"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Customers', url: '/customers' }],
  schema: [
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: FAQ.map(([q, a]) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
      })),
    },
  ],
  sources: [
    ['Dressmaker on Steam (customer and reward wording)', LINKS.steam],
    ['Official itch.io devlog', LINKS.itchDevlog],
  ],
  body: BODY,
};
