import { SHOTS, resolveShots } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const BODY = [
  "Customer preferences in Dressmaker are not a hidden stat sheet. The developers have published no client roster, no preference score and no table of who wants which lace. What you get is a brief: an occasion, a person with their own taste, and a dress to make.",
  "",
  "This page is about the pattern behind those requests, and what it costs to read one wrong. New here? Start with our [dressmaker game](/) overview.",
  "",
  "## What a customer brief is made of",
  "",
  "Every commission has four layers. Only two are said out loud.",
  "",
  "- **The occasion.** A wedding, a formal evening, everyday wear. It sets how much the dress matters.",
  "- **Their taste.** Colour leanings, how much decoration they like, whether they want to be noticed.",
  "- **What they said.** One or two sentences, vague on purpose. That vagueness is the design problem.",
  "- **Your read of them.** What the words leave out: the pause, the fabric they reached for, the dress in your window they keep looking at.",
  "",
  "The official Steam page describes the town as \"people hoping to fill their wardrobes with custom-made dresses tailored specially to important events and their individual tastes.\" Occasion plus taste. The rest is your judgment.",
  "",
  "## Occasion first, taste second",
  "",
  "When the occasion and the customer's taste pull in different directions, build for the occasion and let taste decide the details.",
  "",
  "Say someone wants a wedding dress and loves bold pattern. On a guest's dress that is a choice; against the bride it is a mistake. Keep the silhouette calm and the print small.",
  "",
  "Your own taste steps aside here. The best dress you have designed is worth nothing if it is wrong for the day. In your window you choose the brief; in a commission, it chooses you.",
  "",
  "### The shapes requests fall into",
  "",
  "Briefs seem to arrive in one of three shapes.",
  "",
  "- **The one big day.** A wedding or formal event, and it forgives nothing. Best cloth, restrained decoration, and a practice run in cheap fabric.",
  "- **The dress that has to keep working.** Everyday wear, where wearability beats drama.",
  "- **The open brief.** \"Make me something lovely.\" No plan, so the customer reacts to the dress itself.",
  "",
  "## Reading taste signals",
  "",
  "Customers rarely say what they want precisely. Some of the signals are not words.",
  "",
  "### Colour language",
  "",
  "Listen for colour words that carry attitude, not just hue. \"Something soft\" and \"something cheerful\" want different dresses, even when the swatches sit side by side in your sketchbook.",
  "",
  "### Adjectives",
  "",
  "Adjectives are the closest thing to a specification you will get. *Elegant* means restraint: cleaner lines, fewer accessories, cloth that carries itself. *Fun* means permission to decorate.",
  "",
  "### Hesitation",
  "",
  "A customer who goes quiet when you suggest something has not agreed with you. Hesitation is a soft no; offer a second option and watch which gets the faster answer.",
  "",
  "### What they admire in the window",
  "",
  "Your shop window is a free focus group. Watch which finished dress a customer drifts toward while they talk. A reaction is harder to fake than a request.",
  "",
  "## Turning a vague brief into choices",
  "",
  "When a commission is too thin to design from, find the closest row below and treat it as a starting point.",
  "",
  "> Note: the attribute names below are real, taken from the Requirements box the game shows you before you design. The translation from vague brief language into those attributes is our framework, not official documentation, and the developers have not published a customer list.",
  "",
  "| What the customer says | Silhouette | Fabric | Colour | Trim |",
  "|---|---|---|---|---|",
  "| \"Something like the one in your window\" | Close to the display dress, simplified | The same family as the display piece | What they saw, one step softer | Almost none; the shape is the work |",
  "| \"Whatever you think looks best\" | Your plainest flattering shape | Mid-weight cloth you have sewn before | A colour that suits them, not you | One accent, where the eye lands |",
  "| \"It is for a wedding\" | Formal and structured | The best cloth you can cut twice | Quiet next to the couple | Fine lace, a few buttons, no jokes |",
  "| \"I do not want to stand out\" | Familiar and easy to move in | Matte, textured, forgiving | Muted, near what they wear | Detail only at the edges |",
  "| \"I love this colour\" (hand on a bolt) | Whatever shows the cloth off | That exact fabric, if you can afford it | Their pick; build around it | Trim that echoes, never competes |",
  "| A pause when you suggest something | The opposite of your suggestion | Plainer than the sample you held up | Their first instinct, not your second idea | Back off entirely |",
  "",
  "Notice how often the safe answer is also the polite one. A vague customer is not asking you to gamble; they are asking you to be reliable.",
  "",
  "![A customer in the fitting room reading the dress she was handed in](@SHOT_hero@)",
  "",
  "## How the reward loop works",
  "",
  "Hand a finished dress to a customer and you are paid twice: **coin** and **reputation**. Coin buys fabric; reputation buys the future. The official bullet list says you \"turn in dresses to customers to gain reputation and coin.\"",
  "",
  "### What reputation is for",
  "",
  "Reputation is the slower currency. Good work raises your standing, and better standing brings more interesting commissions over the story. The developers have not published the thresholds, so treat quoted figures with suspicion.",
  "",
  "### Off the rack, for steady income",
  "",
  "The other half of the economy is quieter. You can display your own designs in your shop window and sell pre-made dresses off the rack: nobody's wedding rests on them, and you choose the brief. With roughly **35 hours of story commissions** besides, the rack is steady income.",
  "",
  "## Playing the sabotage run on purpose",
  "",
  "[The official Steam page](@LINK_steam@) invites you to \"satisfy (or sabotage!)\" the townsfolk, an unusual promise for a cozy game to make in writing. It is the freedom to make bad clothes on purpose and watch the town react.",
  "",
  "### Sabotage in practice",
  "",
  "- **Missing the occasion.** Send something grand and theatrical to the customer who asked for everyday wear.",
  "- **Ignoring stated taste.** They told you no pink. Every panel is pink.",
  "- **Clashing fabric and trim.** Heavy velvet under delicate lace, or lace over lace until it stops reading as a dress. You can cut a different fabric for every panel and place trims wherever you like.",
  "- **Decorating past the point of sense.** Buttons, bows and appliqué \"wherever you like\" is the official promise, and exactly the freedom that lets good intentions ruin a silhouette.",
  "",
  "### Why it is funny",
  "",
  "The feedback is a person, not a scoreboard. You hand the dress over and you watch a face. In a game with no combat and no timer, disappointing somebody on purpose is the whole joke.",
  "",
  "### What it costs",
  "",
  "Expect to pay for it. A sabotaged dress does not build the standing that unlocks better work, so play the sabotage run when reputation is not scarce: after the story has given you a cushion, or on a save you do not mind slowing.",
  "",
  "## Recovering from a bad commission",
  "",
  "If you have just handed over a disaster, do not restart. Three things help.",
  "",
  "1. **Practice on the cheapest cloth you can buy.** Make the same dress again in fabric nobody will wear. You are training your eye for layout, not producing a garment.",
  "2. **Take the plain commissions for a while.** An easy dress handed in well is worth more than a risky one handed in badly.",
  "3. **Give the miss a second life.** You can sell your own designs off the rack, so a garment that was wrong for one brief can still earn back part of its fabric.",
  "",
  "Then keep the sketchbook entry. A dress that failed on colour and trim usually had a silhouette that was fine; change the trim next time.",
  "",
  "## Frequently asked questions",
  "",
  "### How many customers are in Dressmaker?",
  "",
  "The developers have not published a customer count or any names, and we will not invent one. The store page promises \"a whole town of people.\"",
  "",
  "### Is there a score or a star rating for a dress?",
  "",
  "Partly. Turning in a dress gives you **coin and reputation**, and the customer's name card also shows a **star rating** - the official screenshots show one card with five stars where only one is lit. What has never been published is how those stars are worked out. The part that is documented is the target: a commission's Requirements box names attributes with numbers, such as **Quality 70, Flowers 60, Cute 30, Romantic 45**, and the fabric shop shows the same scale as commission limits.",
  "",
  "### Do customers remember a bad dress?",
  "",
  "We cannot verify how the town tracks past commissions. What is safe to say is that reputation is the game's standing currency, so a bad turn-in is a slow cost, not a permanent ban.",
  "",
  "### What is the fastest way to build reputation?",
  "",
  "Turn in dresses that match the occasion and the stated taste, and turn them in often. No shortcut or coin-bought standing has been published.",
  "",
  "## Where to go next",
  "",
  "The [how to play Dressmaker](/how-to-play) walkthrough covers the whole sequence: sketchbook, layout, cut, sew, decorate. Our [Dressmaker sewing tips](/sewing-tips) cover the small decisions, the [Dressmaker wiki](/wiki) holds the reference tables, and the [Dressmaker Steam release date](/release-date) page has the launch details.",
].join("\n")
  .split('\n').map((line) => resolveShots(line)).join('\n')
  .replaceAll('@LINK_steam@', LINKS.steam);

// Same answers as the FAQ section in the body, in the shape the FAQPage schema wants.
const FAQ = [
  ["How many customers are in Dressmaker?", "The developers have not published a customer count or any names, and we will not invent one. The store page promises a whole town of people."],
  ["Is there a score or a star rating for a dress?", "Partly. Turning in a dress gives you coin and reputation, and the customer's name card also shows a star rating - the official screenshots show one card with five stars where only one is lit. What has never been published is how those stars are worked out. The part that is documented is the target: a commission's Requirements box names attributes with numbers, such as Quality 70, Flowers 60, Cute 30, Romantic 45, and the fabric shop shows the same scale as commission limits."],
  ["Do customers remember a bad dress?", "We cannot verify how the town tracks past commissions. What is safe to say is that reputation is the game's standing currency, so a bad turn-in is a slow cost, not a permanent ban."],
  ["What is the fastest way to build reputation?", "Turn in dresses that match the occasion and the stated taste, and turn them in often. No shortcut or coin-bought standing has been published."]
];

export const page = {
  url: '/customers',
  title: "Dressmaker Customer Preferences: How to Read a Brief",
  description: "How Dressmaker customer preferences work: read the occasion and taste in a brief, turn it into real design choices, and sabotage on purpose without regret.",
  h1: 'Dressmaker Customer Preferences',
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Customers', url: '/customers' }],
  schema: [
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: FAQ.map(([q, a]) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
      })),
    },
  ],
  body: BODY,
};
