import { resolveFigures } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const BODY = [
  "> Short answer: The Dressmaker demo is a **free prototype on itch.io** — name your own price, Windows, macOS and Linux, about 115–128 MB. It is a standalone 2025 prototype, not a Steam demo of the full game.",
  "",
  "## Free prototype or full game?",
  "",
  "Two different downloads, and it matters which one you want.",
  "",
  "| | Free prototype (itch.io) | Full game (Steam) |",
  "| --- | --- | --- |",
  "| Price | Free, name your own price | **$14.99**, or **$13.49** at launch |",
  "| Platforms | Windows, macOS, Linux | Windows and macOS |",
  "| Size | 115–128 MB | 296 MB download, 1.2 GB installed |",
  "| Contents | The 2025 prototype, with \"a lot of unfinished seams\" | Over 150 dress pieces, 450 fabrics, 350 accessories |",
  "| Story | No length published | About 35 hours of commissions, a town, an ending |",
  "| Pick it if | You want to test the craft for free | You want the actual game |",
  "",
  "![Paper pattern pieces laid out on strawberry-print fabric with shears resting on the cloth](@SHOT_cut@ The same loop runs in both builds: lay out the pattern, cut the cloth, sew, decorate, hand in.)",
  "",
  "## Where the free Dressmaker download is",
  "",
  "The only official free download is the developers' own page: [elyaradine.itch.io/dressmaker](@LINK_itch@). elyaradine is Jonathan Hau-Yoon, one of the three developers, so it is first-party.",
  "",
  "The listing is **name your own price**: clicking **Download Now** opens [the Dressmaker download page](@LINK_itchDownload@), where the price field accepts $0. The current build is **version 0.5.5**.",
  "",
  "| Platform | File | Size |\n|---|---|---|\n| Windows | Dressmaker Prototype Windows 0.5.5.zip | 115 MB |\n| Linux | Dressmaker Prototype Linux 0.5.5.zip | 127 MB |\n| macOS | Dressmaker Prototype OSX 0.5.5.zip | 128 MB |",
  "",
  "> Note: there is **no playable browser version** and **no released mobile or APK version** of Dressmaker. Mobile ports are only something the developers said they are planning. Anything offering either today is unofficial.",
  "",
  "## How to download and run the prototype",
  "",
  "The whole flow, in order.",
  "",
  "::: steps",
  "1. **Open the official page** — [elyaradine.itch.io/dressmaker](@LINK_itch@).",
  "2. **Click Download Now** — itch.io opens a purchase page, because the listing is name your own price.",
  "3. **Enter $0** — or any amount. The files are the same either way.",
  "4. **Pick your zip** — Windows (115 MB), Linux (127 MB) or macOS (128 MB).",
  "5. **Unzip it somewhere you will find again** — not in the zip preview.",
  "6. **Run the game** — on a Mac there is one extra step, and it is next.",
  ":::",
  "",
  "![A green off-the-shoulder dress on a mannequin with the commission completion options](@SHOT_shop@ Hand the dress in, keep working on it, or sell it instead of delivering the commission.)",
  "",
  "## The macOS warning, and the official fix",
  "",
  "> Warning: the macOS build is **not notarized**, because the team has no Apple developer account. macOS refuses to open it and warns that it may be malicious.",
  "",
  "The developers publish their own workaround on the itch page.",
  "",
  "::: steps",
  "1. **Open System Settings** — from the Apple menu.",
  "2. **Go to Privacy & Security**.",
  "3. **Scroll to the security section** — macOS lists the blocked app there. Click **Open Anyway**.",
  "4. **Confirm the choice** — in the second prompt.",
  ":::",
  "",
  "> Note: this is the route the itch page documents. You only need to do it once.",
  "",
  "## What is actually in the prototype",
  "",
  "The prototype is the project the full game grew out of: a **Free Lives project made in about three weeks**, plus **another month or two of work**.",
  "",
  "| In prototype 0.5.5 | Not in prototype 0.5.5 |",
  "| --- | --- |",
  "| Take a commission, choose fabric, cut the pattern, sew, decorate, hand in | A cut-down slice of the Steam release |",
  "| The 2025 itch.io project, still labelled \"Prototype\" | The content-complete September 2026 launch build |",
  "| Free, on Windows, macOS and Linux | Achievements, an ending, Steam Cloud, the town of clients |",
  "| \"A lot of unfinished seams\", per the developers | The full wardrobe of dress pieces, fabrics and accessories |",
  "",
  "![A purple floral gown with lace tiers on a mannequin in photo mode](@SHOT_finished@ The payoff the prototype still delivers: a finished dress on the mannequin, ready for photo mode.)",
  "",
  "### It is not a Steam demo",
  "",
  "No. It is the original standalone prototype at version 0.5.5, and it is not a cut-down slice of the September 2026 Steam release. The two are separate downloads. The [Dressmaker sewing tips](/sewing-tips) page explains grain and bias.",
  "",
  "## What players say about the prototype",
  "",
  "A strong score for something still labelled a prototype, and it rates the free itch build, not the Steam release.",
  "",
  "| Signal | Reading |",
  "| --- | --- |",
  "| itch.io rating | **4.8 out of 5 from 834 ratings** |",
  "| Comments | Roughly **1,208** |",
  "",
  "Read them at [elyaradine.itch.io/dressmaker](@LINK_itch@).",
  "",
  "## Who should download it, and who should skip it",
  "",
  "Four reasons to grab it, and one to skip it.",
  "",
  "::: cards",
  "### You want a free test drive",
  "Cutting, layout and sewing for $0, before you spend $14.99.",
  "### You play on Linux",
  "Steam has no Linux depot, so this is the only build for you.",
  "### You like unfinished builds",
  "Unfinished seams included, exactly as the developers describe it.",
  "### Skip it for the story",
  "The town of clients, the achievements and the ending live in the paid release.",
  ":::",
  "",
  "The only thing you risk is an evening. The [Dressmaker guide to how to play](/how-to-play) walks the same steps in the finished game, and the [dressmaker game](/) overview has the price and the [customer briefs](/customers).",
  "",
  "## Is the full game free?",
  "",
  "No. Asked in the itch.io comments before launch, developer elyaradine answered: \"No, the full [game will not be free].\"",
  "",
  "The Steam release is **$14.99**, or **$13.49** with the 10% launch discount, with no microtransactions and no ads. The [Dressmaker Steam release date](/release-date) page has the bundles.",
  "",
  "## Questions people ask before downloading",
  "",
  "### Is the Dressmaker prototype free?",
  "",
  "Yes. The prototype on itch.io is name your own price, so you can download it for $0 or pay whatever you think it is worth. The paid Steam release is a separate, much bigger game.",
  "",
  "### Is the itch.io prototype a Steam demo?",
  "",
  "No. It is the original standalone prototype at version 0.5.5, and it is not a cut-down slice of the September 2026 Steam release. The two are separate downloads.",
  "",
  "### Is there a browser version or a Dressmaker APK?",
  "",
  "Not today. There is no playable browser version and no released mobile or APK version of Dressmaker. The developers said at launch that mobile ports are being planned, so watch their official channels. Anything offering either right now is unofficial.",
  "",
  "### Do I need a gaming PC to run the prototype?",
  "",
  "The developers have not published system requirements for the itch prototype. For the full game, Steam lists minimum specifications only, with no recommended tier. The [Dressmaker system requirements](/system-requirements) page has both tables.",
  "",
  "### Is the prototype still being updated?",
  "",
  "The current download is version 0.5.5, and the developers have not published a roadmap for further prototype updates. The \"coming soon\" content in the September devlog is for the full game.",
  "",
  "### What if it will not launch?",
  "",
  "Start with [Dressmaker troubleshooting](/troubleshooting). On macOS the notarization warning is expected. The team also links its Discord from the itch page.",
].join("\n")
  .split('\n').map((line) => resolveFigures(line)).join('\n')
  .replaceAll('@LINK_itch@', LINKS.itch)
  .replaceAll('@LINK_itchDownload@', LINKS.itchDownload);

const FAQ = [
  [
    "Is the Dressmaker prototype free?",
    "Yes. The prototype on itch.io is name your own price, so you can download it for $0 or pay whatever you think it is worth. The paid Steam release is a separate, much bigger game."
  ],
  [
    "Is the itch.io prototype a Steam demo?",
    "No. It is the original standalone prototype at version 0.5.5, and it is not a cut-down slice of the September 2026 Steam release. The two are separate downloads."
  ],
  [
    "Is there a browser version or a Dressmaker APK?",
    "Not today. There is no playable browser version and no released mobile or APK version of Dressmaker. The developers said at launch that mobile ports are being planned, so watch their official channels. Anything offering either right now is unofficial."
  ],
  [
    "Do I need a gaming PC to run the prototype?",
    "The developers have not published system requirements for the itch prototype. For the full game, Steam lists minimum specifications only, with no recommended tier."
  ],
];

export const page = {
  url: '/demo',
  title: "Dressmaker Demo: Free Prototype Download on itch.io",
  description: "The Dressmaker demo is a free, name-your-own-price prototype on itch.io: Windows, macOS and Linux downloads, file sizes and the macOS fix.",
  h1: 'Dressmaker Demo and Free Download',
  eyebrow: "Free prototype",
  lede: "The free Dressmaker demo is the prototype on the developers' own itch.io page: elyaradine.itch.io/dressmaker. It is name your own price, so you can take it for $0, and it runs on Windows, macOS and Linux. It is the only official free download that exists.",
  facts: [
    ['Price', "Free, name your own price"],
    ['Where', "itch.io, the developers’ own page"],
    ['Platforms', "Windows, macOS and Linux"],
    ['Download', "About 115–128 MB"],
    ['Version', "Prototype 0.5.5"],
    ['Rating', "4.8 of 5 from 834 ratings"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Demo', url: '/demo' }],
  schema: [
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: FAQ.map(([q, a]) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
      })),
    },
  ],
  sources: [
    ['Dressmaker prototype on itch.io', LINKS.itch],
    ['itch.io download page', LINKS.itchDownload],
    ['itch.io devlog', LINKS.itchDevlog],
  ],
  body: BODY,
};
