import { LINKS } from '../data/site.mjs';

const BODY = [
"## Not affiliated with the developers",
"",
"dressmakerguide.com is an **unofficial fan site**. It is not affiliated with, endorsed by, sponsored by, approved by or connected to the Dressmaker development team, Cozy Lives, Free Lives, Valve Corporation, itch.io, or any of their subsidiaries or partners.",
"",
"Nothing on this site is an official statement. Nothing here should be read as a promise about the game's content, price, features, platform support or release schedule. For anything official, use the [Steam store page](" + LINKS.steam + "), the [official Steam announcements](" + LINKS.steamNews + ") and the [itch.io devlog](" + LINKS.itchDevlog + ").",
"",
"## Copyright and trademarks",
"",
"\"Dressmaker\", the Dressmaker logo, character art, screenshots, music and all related assets are the property of their respective owners. They appear on this site for **identification, commentary, criticism and review** only.",
"",
"- We do not host or redistribute the game, its build files, its assets or its soundtrack.",
"- Download and purchase links point to the developers' own pages.",
"- Our own graphics (the site mark, the Open Graph card and the diagrams) are original to this site.",
"- If you are a rights holder and you want an image, a quote or a page changed or removed, email us via the [contact page](/contact) and we will act on it promptly. You do not need to involve a lawyer to get a fast answer from us.",
"",
"## Accuracy, and how we handle uncertainty",
"",
"We check facts against primary sources - the official Steam store page, the official Steam news hub, the itch.io prototype page and the official devlog. Where the developers have not published something, we say so rather than guessing.",
"",
"That said: prices change, launch discounts expire, specifications get edited, patches land. **Always treat the official Steam page as more current than this site.** Pages here carry a last-updated date; if a page looks stale, assume it might be.",
"",
"If you spot an error, please [report it](/contact). Corrections are welcome and are made quickly.",
"",
"## No professional advice",
"",
"Guides on this site are about how to play a video game. They are not legal, financial, medical or professional advice of any kind. The same goes for our [system requirements](/system-requirements) page, which explains what the developers published rather than recommending hardware purchases.",
"",
"Real-world dressmaking is a genuine trade with real techniques, real risks and real safety considerations around cutting tools, machines and irons. If you want to sew real garments, learn from a qualified instructor or a reputable published source. This site cannot teach you that, and does not try.",
"",
"## Advertising and independence",
"",
"This site may display advertising, including through Google AdSense and other ad networks, to cover hosting costs. Advertising is served by third parties, every ad slot is labelled as an advertisement, and advertising is never mixed into editorial content.",
"",
"- We do not accept payment for reviews, rankings or placement.",
"- We do not run sponsored posts or paid links.",
"- Advertisers have no input into what we write.",
"",
"See the [privacy policy](/privacy) for how advertising cookies work and how to turn them off.",
"",
"## Availability and liability",
"",
"This site is provided \"as is\", without warranties of any kind. We do not guarantee that it will be available, error-free or complete, and we are not liable for any loss arising from reliance on its contents - including, but not limited to, buying a game you turn out not to enjoy, or a purchase made on the basis of an out-of-date price. Check the store page before you buy.",
"",
"External links are provided for convenience. We do not control those sites and are not responsible for their content, their policies or their accuracy.",
"",
"## Trademark notice for search engines and readers",
"",
"If you arrived here searching for **dressmaker**, **dressmaker game**, **dressmaker demo** or **dressmaker steam**, you are in the right place for the video game. If you arrived searching for dressmaking patterns, tailoring courses or the dressmaking profession, you are not: this site covers a cozy simulation game, not a trade. Our [games like Dressmaker](/games-like) page is a better starting point if you want more games in this style.",
].join("\n");

export const page = {
  url: '/disclaimer',
  title: 'Disclaimer | Dressmaker Guide Fan Site',
  description: 'dressmakerguide.com is an unofficial Dressmaker fan site with no developer affiliation. Read our copyright, accuracy and liability disclaimers.',
  h1: 'Disclaimer',
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Disclaimer', url: '/disclaimer' }],
  body: BODY,
};
