import { SHOTS, resolveShots } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const SHOT_cut = SHOTS.cut.src;

const BODY = [
  "> Short answer: If you want the feeling of Dressmaker without the dressmaking, start with **Unpacking**, **A Little to the Left** or **Wilmot's Warehouse** for tactile organising, and **Calico** or **Strange Horticulture** for cozy making with a shop attached. None of them replace Dressmaker's fabric-layout mechanic, which is the part that is genuinely unusual.",
  "",
  "Most cozy lists hand you farming sims and shop-management games. Dressmaker is neither: the [dressmaker game](/) is about making one beautiful thing with your hands, and the shop is scaffolding around that.",
  "",
  "![Paper pattern pieces laid out on strawberry-print fabric with shears resting on the cloth](@SHOT_cut@ Pattern pieces laid on the cloth decide what the dress will look like. Then the shears decide it permanently.)",
  "",
  "## How to choose",
  "",
  "Match the itch you actually have, not the genre label.",
  "",
  "| If you want... | Play this |",
  "| --- | --- |",
  "| The making: cutting, sewing, a garment coming together | **Potion Craft: Alchemist Simulator**, **Strange Horticulture** |",
  "| The decorating: placing buttons, bows and lace by hand | **Calico**, **House Flipper**, **Town to City** |",
  "| The organizing: fitting pattern pieces onto a bolt without waste | **Unpacking**, **A Little to the Left**, **Wilmot's Warehouse** |",
  "| A surface changing under your hands, with nothing to design | **PowerWash Simulator** |",
  "| The town more than the dress | **Stardew Valley** |",
  "",
  "## Ten cozy games like Dressmaker",
  "",
  "One line each on what it shares with Dressmaker, and where it falls short.",
  "",
  "::: cards",
  "### Unpacking (2021)",
  "A wordless puzzle game about emptying boxes into a new home and giving every object a place. The most tactile game here, but you are arranging a life that already exists rather than designing something new.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/1135690/Unpacking/)",
  "### A Little to the Left (2022)",
  "Tidy a shelf or a drawer until the arrangement feels right, then watch a cat wreck it. The same calm, fiddly pleasure as fitting pattern pieces onto a bolt, except every puzzle here has an intended answer.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/1629520/A_Little_to_the_Left/)",
  "### Wilmot's Warehouse (2019)",
  "Sort tiles into a warehouse layout that only you understand, then remember it when an order arrives. Dressmaker's quiet spatial thinking with no aesthetic at all: there is no right-looking answer, only a system that works.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/839870/Wilmots_Warehouse/)",
  "### Potion Craft: Alchemist Simulator (2022)",
  "Grind herbs, stir the cauldron, draw a path across the alchemy map, then sell the bottle to whoever walks in. The closest thing here to the sewing machine, though alchemy has correct answers where dressmaking has taste.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/1210320/Potion_Craft_Alchemist_Simulator/)",
  "### Strange Horticulture (2022)",
  "Identify plants by leaf shape and smell, file them into your collection and set them out for customers with specific needs. Handling specimens and matching them to a request is very close to Dressmaker's counter loop, but there is a dark occult mystery and endings you can get wrong.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/1574580/Strange_Horticulture/)",
  "### Calico (2020)",
  "Run a cat cafe in a town of magical girls and talking animals, and decorate it however you like. That freedom to place things purely because they look good is the Dressmaker feeling, spread thinner across many small activities.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/1112890/Calico/)",
  "### House Flipper (2018)",
  "Buy a wreck, clean it, repair it, knock down walls and furnish every room, then sell it. The decorating half of Dressmaker stretched into a whole game, minus the restraint: the goal is a profitable sale, not a client's reaction.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/613100/House_Flipper/)",
  "### PowerWash Simulator (2022)",
  "Point a power washer at something filthy and watch the grime come off in strips until the surface gleams. The purest physical satisfaction on this list, and the least creative: there is exactly one correct result, and it is clean.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/1290000/PowerWash_Simulator/)",
  "### Stardew Valley (2016)",
  "Farm, craft, fish and cook in a town whose tastes, schedules and opinions you slowly learn to read. The pick if you miss the town more than the dress, though it runs on a daily clock, seasons and energy, and it will send you into a mine with a sword.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/413150/Stardew_Valley/)",
  "### Town to City",
  "Compose a street from houses, trees and lamp posts until it looks the way you imagined. It shipped alongside Dressmaker in the \"Dressmaker X Town to City\" bundle, 10% off each game, and it is placement at the scale of a town.",
  "",
  "Where to play: [Steam](https://store.steampowered.com/app/3115220/Town_to_City/)",
  ":::",
  "",
  "## What none of these can replace",
  "",
  "> Note: none of the ten replaces Dressmaker's fabric-layout mechanic. Pattern pieces go onto a bolt, where you put them is what ends up on the dress, and the cut is permanent.",
  "",
  "Aligned to the grain the cloth reads neat and even. Cut on the bias the same cloth behaves differently, and every panel can use a different fabric. The [how to play Dressmaker](/how-to-play) walkthrough covers that stage in full.",
  "",
  "So treat this list as a substitute for the feeling, not the feature. Dressmaker released on September 21, 2026 on Steam for Windows and macOS at $14.99, with a 10% launch discount to $13.49. The [Dressmaker release date](/release-date) page has the details, and the free itch.io prototype on the [demo page](/demo) is the cheapest way to find out whether the cutting rhythm clicks.",
  "",
  "## The list at a glance",
  "",
  "| Game | What it scratches | Platform |",
  "| --- | --- | --- |",
  "| Unpacking | Placing every object by hand until a room feels finished | Windows, macOS, Linux |",
  "| A Little to the Left | Tidying a small space into a satisfying arrangement | Windows, macOS |",
  "| Wilmot's Warehouse | Sorting a layout that only makes sense to you | Windows, macOS |",
  "| Potion Craft: Alchemist Simulator | Hands-on making at a workbench, one item at a time | Windows |",
  "| Strange Horticulture | Handling materials and matching them to a request | Windows, macOS |",
  "| Calico | Decorating a space purely because it looks good | Windows, macOS |",
  "| House Flipper | Cleaning, repairing and furnishing a room until it sings | Windows, macOS |",
  "| PowerWash Simulator | The plain physical joy of a surface coming clean | Windows |",
  "| Stardew Valley | A town whose tastes you slowly learn to read | Windows, macOS, Linux |",
  "| Town to City | Composing a view with nobody rushing you | Windows |",
  "",
  "Every Steam link on this page goes to that game's own store listing, and each platform list comes from the same listing. Dressmaker itself is a Windows and macOS release on [Steam](@LINK_steam@)."
].join("\n")
  .split('\n').map((line) => resolveShots(line)).join('\n')
  .replaceAll('@LINK_steam@', LINKS.steam);

export const page = {
  url: '/games-like',
  title: 'Games Like Dressmaker: 10 Cozy Crafting Picks',
  description: 'Ten cozy games like Dressmaker, picked for hands-on making, decorating and organizing, with Steam links and an honest note on what none of them replace.',
  h1: 'Games Like Dressmaker',
  eyebrow: "Recommendations",
  lede: "If you go looking for games like Dressmaker, most cozy lists hand you farming sims and shop-management games. Dressmaker is neither. The dressmaker game is about making one beautiful thing with your hands: choosing the fabric, laying out the pattern pieces, cutting, sewing, decorating. The shop is scaffolding around that.",
  facts: [
    ['Closest match', "Unpacking"],
    ['For organising', "A Little to the Left, Wilmot’s Warehouse"],
    ['For cozy making', "Calico, Strange Horticulture"],
    ['For town life', "Stardew Valley"],
    ['Launch bundle', "Town to City"],
    ['Unreplaceable', "The fabric-layout mechanic"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Games Like Dressmaker', url: '/games-like' }],
  sources: [
    ['Dressmaker on Steam', LINKS.steam],
    ['Official itch.io devlog', LINKS.itchDevlog],
  ],
  body: BODY,
};
