import { SHOTS, resolveShots } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const SHOT_cut = SHOTS.cut.src;
const SHOT_sew = SHOTS.sew.src;

const BODY = [
  "> Short answer: To play Dressmaker, read the customer's brief, design in the sketchbook, choose fabric and color, lay out the pattern, cut, sew, decorate and hand the dress in for coin, reputation and a star rating. Read the brief before you design; preview the layout before you cut.",
  "",
  "## The five stages",
  "",
  "Nothing is timed, and the only things you can lose are cloth and coin.",
  "",
  "| Stage | What you decide | What it costs you |",
  "| --- | --- | --- |",
  "| Sketchbook | Silhouette, color, samples, appliqué | A design you cannot supply |",
  "| Fabric | Which bolt goes on which panel | Cloth that fights the design |",
  "| Layout and cutting | Grain or bias, and piece placement | A permanent mark on the dress |",
  "| Sewing | Seam order and alignment | Panels that fit together badly |",
  "| Decorating | Buttons, bows, appliqué, lace | Trim that buries the fabric |",
  "",
  "## The first five minutes",
  "",
  "You start in the shop: counter, fabric shelves, sewing machine, mannequin, sketchbook. No control list is published, so here is the order of play.",
  "",
  "::: steps",
  "1. **Go to the customer** — read the commission before anything else.",
  "2. **Open the sketchbook** — every dress starts as a design, not a bolt.",
  "3. **Check your stock** — samples you cannot buy, you cannot cut.",
  "4. **Walk the room** — look at the bolts, pet the kitty.",
  ":::",
  "",
  "## Reading a commission",
  "",
  "Every client arrives with an important event to dress for and their own taste — \"tailored specially to important events and their individual tastes.\"",
  "",
  "| What you need | Where it comes from |",
  "| --- | --- |",
  "| The occasion | The customer's own words at the counter |",
  "| Their taste | The conversation: colors, reactions, word choice |",
  "| The numbers | The sketchbook Requirements box |",
  "",
  "> Note: the brief is the only free part of a commission. The full attribute list is unpublished, so target names vary by client.",
  "",
  "## The sketchbook: designing before you cut",
  "",
  "Official wording: you \"design and colour your dress in your sketchbook, adding fabric samples and appliqué.\"",
  "",
  "::: steps",
  "1. **Silhouette first** — the shape decides your pattern pieces.",
  "2. **Color second** — free and reversible at this stage.",
  "3. **Fabric samples third** — so the mock-up uses stock you own.",
  "4. **Appliqué last** — plan it here, place it after sewing.",
  ":::",
  "",
  "> Note: the full game carries **over 150 dress pieces and over 350 accessories**. A silhouette is free to change now and expensive after the cut.",
  "",
  "## Buying and choosing fabric",
  "",
  "The store names cotton, linen, wool, silk and velvet among **over 450 fabrics**. No stats are published, so judge cloth the way a dressmaker does.",
  "",
  "| Judge it by | Why it matters |",
  "| --- | --- |",
  "| Drape | Stiff cloth holds a shape; soft cloth collapses into folds |",
  "| Print scale | A large print is chopped up the moment you cut a bodice |",
  "| Cost | No price list exists; the bolt you buy is the bolt you must make work |",
  "| Panels | You pick the fabric for each panel: a cotton bodice, a silk skirt |",
  "",
  "## Pattern layout: grain, bias and the preview",
  "",
  "The official [Steam store page](@LINK_steam@) puts it plainly: how you arrange and cut out your fabric \"is what appears on the final dress.\"",
  "",
  "| Placement | Aligned to the grain | Cut on bias |",
  "| --- | --- | --- |",
  "| What it is | Lined up with the threads of the weave | A diagonal cut across that weave |",
  "| How it behaves | Straight, stable, even | More give and a different hang |",
  "| When to choose it | For panels that must stay square | As a deliberate look, never as a fix |",
  "",
  "> Tip: preview every layout on the mannequin before you cut. It is the last free check you get.",
  "",
  "![Paper pattern pieces laid out on strawberry-print fabric with shears resting on the cloth](@SHOT_cut@ Pattern pieces laid on the cloth decide what the dress will look like. Then the shears decide it permanently.)",
  "",
  "## Cutting: the point of no return",
  "",
  "Plan the whole layout before the first cut.",
  "",
  "> Warning: cutting is permanent. No seam fixes a panel cut at the wrong angle, and no trim hides a motif sliced in half.",
  "",
  "- **Place every piece** the design needs, not just the biggest.",
  "- **Check print direction** — directional cloth cannot be flipped.",
  "- **Mind the waste** — leftover cloth is coin.",
  "",
  "## Sewing: feeding fabric through the machine",
  "",
  "Official wording: \"Feed your fabric through the sewing machine to stitch it together.\" The screenshot caption promises \"a sewing machine with infinite bobbin,\" so there is no spool to manage.",
  "",
  "- **Structural seams first** — panels must meet edge to edge.",
  "- **No seam sequence is published** — think the order through first.",
  "",
  "![Fabric being fed through a sewing machine with the stitch prompts shown on screen](@SHOT_sew@ Panels go through the machine one seam at a time, with the controls on screen as you go.)",
  "",
  "## Decorating: buttons, bows, appliqué and lace",
  "",
  "Buttons, bows, appliqué and lace trims go on \"wherever you like with complete creative freedom.\"",
  "",
  "- **Busy print** — keep trim near the edges.",
  "- **Plain silhouette** — decoration is where the personality comes from.",
  "- **Three good ideas** — a loud print, heavy lace and a big bow compete.",
  "",
  "## Turning in the dress",
  "",
  "Hand the dress to the customer, or sell your own designs off the rack. Story commissions run about **35 hours**, excluding off-rack work.",
  "",
  "| What you do | What you get |",
  "| --- | --- |",
  "| Meet the brief | Coin, reputation and a good star rating |",
  "| Miss the brief | Less coin, and you see it in the customer's reaction |",
  "| Sell off the rack | Steady coin, with nobody's wedding depending on it |",
  "",
  "One official hand-in line reads: \"Oh, how wonderful. This is MY dress, exactly as I wanted it.\"",
  "",
  "> Note: coin and reputation are the feedback loop. No coin table, reputation threshold or star formula has ever been published.",
  "",
  "## How your dress is scored",
  "",
  "A commission is not judged on vibes: the sketchbook lists **named attributes with numeric targets**.",
  "",
  "| Where you see it | What it looks like | What it means |",
  "| --- | --- | --- |",
  "| Sketchbook, Requirements box | Quality 70, Flowers 60, Cute 30, Romantic 45 | What this customer judges you on |",
  "| Sketchbook, budget | 800, and roughly 3.85m of fabric required | What you can afford to spend |",
  "| Fabric shop, commission limits | Quality 0/80, Formal 0/50, Simple 0/75, Professional 0/50 | Progress against a ceiling |",
  "| Fabric shop, hard rule | \"Use only black\" | Non-negotiable, beats taste |",
  "| Name card at hand-in | A star rating | How the dress landed, in stars |",
  "",
  "- **Read the targets before you design.** A brief asking for 60 Flowers wants floral cloth and trim.",
  "- **Not every brief names the same attributes.** The garden-party commission lists four.",
  "- **Limits are ceilings too.** A **Simple 0/75** line caps how much decoration the customer wants.",
  "- **Hard rules beat taste.** Black only means a pink silk fails.",
  "",
  "> Note: the two numbers in a limit pair read as progress against a ceiling, but the game never labels them. The attribute list and star formula are unpublished.",
  "",
  "## Beginner mistakes",
  "",
  "| Mistake | Why it costs you | What to do instead |",
  "| --- | --- | --- |",
  "| Designing before reading the brief | You build a dress nobody asked for | Read the targets, then sketch |",
  "| Designing a dress you cannot afford | Coin spent on cloth that fights the design | Settle the fabric in the sketchbook |",
  "| Rushing the shears | A bad layout shows on the dress forever | Preview, then cut once |",
  "| Ignoring print scale | A large motif disappears into small panels | Big prints on big panels |",
  "| Cutting on the bias by accident | Bias is a look, not a way to make a piece fit | Choose bias on purpose |",
  "| Over-decorating | Trim buries the fabric you paid for | Keep trim near the edges |",
  "",
  "## What to do next",
  "",
  "Start on the [dressmaker game](/) homepage. [Dressmaker sewing tips](/sewing-tips) covers seam order and grain, [customer preferences](/customers) covers reading a brief, and the [Dressmaker wiki](/wiki) is the reference tab. Test the loop free on the [itch.io prototype](/demo)."
].join("\n")
  .split('\n').map((line) => resolveShots(line)).join('\n')
  .replaceAll('@LINK_steam@', LINKS.steam);

export const page = {
  url: '/how-to-play',
  title: 'How to Play Dressmaker: Cutting, Sewing & Design',
  description: 'How to play Dressmaker step by step: read the commission, sketch the design, choose fabric, lay out the pattern, cut, sew, decorate and turn the dress in.',
  h1: 'How to Play Dressmaker',
  eyebrow: "Walkthrough",
  lede: "Dressmaker is a cozy crafting game about making one dress, for one person, for one occasion. A customer walks in with a request, you design in your sketchbook, buy fabric, arrange pattern pieces, cut, sew, decorate and hand the dress over.",
  facts: [
    ['The loop', "Brief, design, cut, sew, decorate, hand in"],
    ['Decide first', "Read the brief before you design"],
    ['Never skip', "The mannequin preview"],
    ['Paid in', "Coin, reputation and a star rating"],
    ['Cutting', "Permanent — there is no undo"],
    ['Time to learn', "About 30 minutes to the first good dress"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  preload: SHOT_cut,
  crumbs: [{ name: 'Home', url: '/' }, { name: 'How to Play', url: '/how-to-play' }],
  schema: [
    {
      '@context': 'https://schema.org',
      '@type': 'HowTo',
      name: 'How to play Dressmaker',
      description: 'The full Dressmaker play loop: commissions, sketchbook design, fabric choice, pattern layout, cutting, sewing, decorating and turning a dress in.',
      step: [
        { '@type': 'HowToStep', name: 'Read the commission', text: 'Talk to the customer at the counter and note the occasion and their personal taste before designing anything.' },
        { '@type': 'HowToStep', name: 'Design in the sketchbook', text: 'Choose the silhouette and color, add fabric samples and applique, and confirm your shop stocks what the design needs.' },
        { '@type': 'HowToStep', name: 'Choose fabric', text: 'Buy bolts of cotton, linen, wool, silk or velvet, judging drape, print scale and cost. You can use a different fabric for each panel.' },
        { '@type': 'HowToStep', name: 'Lay out the pattern', text: 'Arrange the pattern pieces on the cloth, deciding grain or bias placement, and preview the result on the mannequin.' },
        { '@type': 'HowToStep', name: 'Cut the fabric', text: 'Cutting is irreversible, so plan the whole layout first. Waste fabric is coin.' },
        { '@type': 'HowToStep', name: 'Sew the panels', text: 'Feed the fabric through the sewing machine. The bobbin is infinite, so the challenge is seam order and alignment.' },
        { '@type': 'HowToStep', name: 'Decorate the dress', text: 'Add buttons, bows, applique and lace trims wherever you like with complete creative freedom.' },
        { '@type': 'HowToStep', name: 'Turn the dress in', text: 'Hand the finished dress to the customer for coin and reputation, or display your own designs in the shop window and sell them off the rack.' },
      ],
    },
  ],
  sources: [
    ['Dressmaker on Steam (official feature list)', LINKS.steam],
    ['Official Steam announcements', LINKS.steamNews],
  ],
  body: BODY,
};
