import { SHOTS, resolveFigures } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const SHOT_hero = SHOTS.hero.src;
const SHOT_cut = SHOTS.cut.src;
const SHOT_sew = SHOTS.sew.src;
const SHOT_decorate = SHOTS.decorate.src;

const BODY = [
  "> Short answer: Dressmaker is a cozy dressmaking simulation where you take a commission, cut the pattern, sew the dress and hand it in. It released on **Steam on September 21, 2026** for Windows and macOS at **$14.99**, and a **free prototype is on itch.io**.",
  "",
  "## Quick reference",
  "",
  "Everything a first-time visitor needs, in one table.",
  "",
  "| Question | Answer |",
  "| --- | --- |",
  "| What is it? | A cozy dressmaking sim: choose fabric, cut patterns, sew, decorate, hand in |",
  "| Out now? | Yes, released **September 21, 2026** |",
  "| Price | **$14.99**, or **$13.49** with the 10% launch discount |",
  "| Platforms | **Windows and macOS** on Steam; Windows, macOS and Linux for the free prototype |",
  "| Free to try? | Yes: the **prototype on itch.io** is name-your-own-price |",
  "| How long? | About **35 hours** of story commissions, plus off-rack dresses |",
  "| Made by | **Cozy Lives** (three developers), published by **Free Lives** |",
  "| Microtransactions? | None. No ads, no data harvesting, no generative AI art |",
  "",
  "## What is Dressmaker?",
  "",
  "A making game, not a shop-management game. Almost every minute happens at the table: cloth in front of you, pattern pieces in hand, deciding what goes where.",
  "",
  "::: cards",
  "### Your layout is permanent",
  "Where you place a pattern piece is exactly what shows on the finished dress. Nothing later undoes a bad cut.",
  "### Real dressmaking words",
  "Grain, bias, panels, appliqué. The game uses the real vocabulary and then shows you what it does.",
  "### You can be a menace",
  "The official pitch invites you to satisfy **or sabotage** your customers. Send the mayor's daughter out in clashing velvet if you like.",
  ":::",
  "",
  "![A purple floral gown with lace tiers displayed on a mannequin in photo mode](@SHOT_finished@ Where all of this ends: a finished gown on the mannequin, with photo mode open to frame the shot.)",
  "",
  "## The loop, in five stages",
  "",
  "Each stage is one decision and one cost. The [full how to play Dressmaker walkthrough](/how-to-play) covers every screen.",
  "",
  "::: steps",
  "1. **Read the commission** — the customer brings an occasion, a taste and a budget.",
  "2. **Design in the sketchbook** — silhouette, colour, fabric samples, appliqué.",
  "3. **Buy fabric and lay out the pattern** — each bolt has a print, a direction and a price.",
  "4. **Cut, then sew** — cutting is permanent; the sewing machine has an infinite bobbin.",
  "5. **Decorate and hand in** — buttons, bows and lace, then coin, reputation and a star rating.",
  ":::",
  "",
  "> Warning: cutting is the point of no return. Fabric is spent the moment the shears go through it.",
  "",
  "![Fabric being fed through a sewing machine with the stitch prompts shown on screen](@SHOT_sew@ Stage four up close: the panels go through the machine one seam at a time, with the controls on screen.)",
  "",
  "## How your dress is scored",
  "",
  "A commission is not judged on vibes. The sketchbook lists **named attributes with numeric targets**, and your dress is measured against them.",
  "",
  "| Where you see it | What it looks like | What it means |",
  "| --- | --- | --- |",
  "| Sketchbook, Requirements box | Quality 70, Flowers 60, Cute 30, Romantic 45 | What this customer will judge you on |",
  "| Sketchbook, budget | 800, and roughly 3.85m of fabric | What you can afford to spend |",
  "| Fabric shop, commission limits | Quality 0/80, Formal 0/50, Simple 0/75, Professional 0/50 | Progress against a ceiling |",
  "| Fabric shop, hard rule | \"Use only black\" | Non-negotiable, beats taste |",
  "| Customer card at hand-in | A star rating | How the dress landed, in stars |",
  "",
  "The developers have never published the full attribute list, so expect names to vary by client. [Customer preferences](/customers) covers how to read a brief.",
  "",
  "![The sketchbook open on a customer note with dress requirements and pattern choices](@SHOT_sketch@ The sketchbook is where the brief and its numeric targets live before any cloth is cut.)",
  "",
  "## Demo and download",
  "",
  "Two different downloads, and it matters which one you want.",
  "",
  "| | Free prototype (itch.io) | Full game (Steam) |",
  "| --- | --- | --- |",
  "| Price | Free, name your own price | **$14.99** / **$13.49** at launch |",
  "| Platforms | Windows, macOS, Linux | Windows, macOS |",
  "| Size | 115–128 MB | About 1.2 GB installed |",
  "| Contains | A 2025 prototype with \"a lot of unfinished seams\" | Story, town of clients, achievements, an ending |",
  "| Why pick it | To test the cutting and sewing loop for free | To play the actual game |",
  "",
  "The prototype is **not** a Steam demo. It is a separate, older build. The [Dressmaker demo and download](/demo) page has the direct link and the macOS Gatekeeper fix.",
  "",
  "![Paper pattern pieces laid out on strawberry-print fabric with shears resting on the cloth](@SHOT_cut@ The free prototype is where you can lay out a pattern and cut it before paying for the full game.)",
  "",
  "## Release details",
  "",
  "| | Detail |",
  "| --- | --- |",
  "| Released | **September 21, 2026**, the announced date, kept |",
  "| US price | **$14.99**, with a time-limited **10%** launch discount to **$13.49** |",
  "| Steam App ID | 4019220 |",
  "| Developer | **Cozy Lives** — Jonathan Hau-Yoon, Sara Laubscher, Ruan Rothmann |",
  "| Publisher | **Free Lives** |",
  "| Achievements | 32, plus Steam Cloud and mouse-only play |",
  "| Post-launch | More free content planned: challenge mode, transparent fabrics, controller support |",
  "",
  "The [Dressmaker Steam release date](/release-date) page tracks bundles, regional pricing and how to catch a sale.",
  "",
  "## Beginner tips",
  "",
  "::: steps",
  "1. **Align the pattern to the grain** — bias cuts are a deliberate choice, not an accident.",
  "2. **Keep big prints off small panels** — a large floral loses its shape on a bodice.",
  "3. **Preview on the mannequin every time** — it is the last free check you get.",
  ":::",
  "",
  "> Tip: while you are learning, buy the cheapest cloth that meets the brief. Save silk and velvet for commissions that pay.",
  "",
  "There is a longer list, including seam order and trim discipline, on the [Dressmaker guide and sewing tips](/sewing-tips) page.",
  "",
  "## Customers and rewards",
  "",
  "| You give | You get |",
  "| --- | --- |",
  "| A dress that meets the brief | Coin, reputation, a good star rating |",
  "| A dress that misses the brief | Less coin, and you will see it in the reaction |",
  "| A dress sold off the rack | Steady coin, with nobody's wedding depending on it |",
  "",
  "Reputation opens better commissions. The [Dressmaker customer preferences](/customers) page covers reading a brief and playing the sabotage run on purpose.",
  "",
  "![A customer in the fitting room reading the dress she was handed in](@SHOT_hero@ A finished dress always ends with a customer reaction.)",
  "",
  "## System requirements",
  "",
  "Steam publishes a minimum tier only — there is no recommended specification.",
  "",
  "| Platform | Minimum |",
  "| --- | --- |",
  "| Windows | Windows 10 or later, Intel Core i5 or AMD Ryzen, 8 GB RAM, Intel UHD 630 or better, DirectX 11, 1 GB storage |",
  "| macOS | Apple M1, 8 GB RAM, 1 GB storage |",
  "",
  "The install is about **1.19 GiB on Windows** and **1.22 GiB on macOS**, a download of roughly 300 MB. Full detail is on the [Dressmaker system requirements](/system-requirements) page.",
  "",
  "## Games like Dressmaker",
  "",
  "::: cards",
  "### Unpacking",
  "The closest match: tactile, wordless, about putting one thing in the right place.",
  "### A Little to the Left",
  "Organising as comfort. Same low-pressure loop, no fabric involved.",
  "### Calico",
  "Cozy making with a shop attached, and a gentler difficulty curve.",
  ":::",
  "",
  "Ten recommendations, each with an honest note on what it does differently, are on the [games like Dressmaker](/games-like) page.",
  "",
  "## Reference tables",
  "",
  "Fabrics, pattern pieces, decorations and a glossary live in the [Dressmaker wiki](/wiki). Keep it open in a second tab.",
  "",
  "## Frequently asked questions",
  "",
  "### Is Dressmaker a real game or just a demo?",
  "",
  "Both exist, and they are separate builds. The free prototype on itch.io is a substantial slice that players have rated 4.8 out of 5. The paid Steam release is the full game, with story commissions, a town of clients, achievements and an ending.",
  "",
  "### Is Dressmaker free?",
  "",
  "The itch.io prototype is free on a name-your-own-price basis. The full Steam release costs **$14.99** in the US, with a **10% launch discount** to **$13.49**.",
  "",
  "### When did Dressmaker come out?",
  "",
  "Dressmaker released on Steam on **September 21, 2026** for Windows and macOS. The free prototype has been on itch.io since 2025.",
  "",
  "### Is this the same as DressMaker or DressMaker Pro on Steam?",
  "",
  "No, and it is worth knowing before you buy the wrong thing. There are two other games on Steam called DressMaker and DressMaker Pro, both released in 2021, and both are 3D character design tools rather than games. This page is about Dressmaker by Cozy Lives and Free Lives, the cozy dressmaking sim that released on September 21, 2026. If the store page you are looking at mentions character rigging or game development, you are on the wrong one.",
  "",
  "### Is Dressmaker on Nintendo Switch, PlayStation or Xbox?",
  "",
  "Not yet. The released game is Windows and macOS on Steam, plus the Windows, macOS and Linux prototype on itch.io. In the launch-day Steam announcement the developers said they are **planning mobile and Switch ports**, so a console version is on the roadmap rather than available today.",
  "",
  "### Is there a Dressmaker mobile app or a browser version I can play now?",
  "",
  "No playable mobile or browser version exists today, and we will not pretend otherwise. The developers did say on launch day that mobile ports are being planned, so expect an official announcement before any real app appears. Any site offering a \"Dressmaker APK\" or an online playable version right now is not affiliated with the developers.",
  "",
  "### How long is Dressmaker?",
  "",
  "The developers describe roughly **35 hours of story commissions**, before off-rack dresses, decorating for fun and the post-launch content they have said is still coming.",
  "",
  "### Is Dressmaker made with AI?",
  "",
  "No. The developers have said the game is privately owned and made by hand, and the itch.io prototype carries the \"No generative AI was used\" tag. Art, code and music are credited to named people.",
  "",
  "### Is Dressmaker hard?",
  "",
  "It is gentle by design — there is no timer and no fail state in the usual sense. The difficulty is that cutting is irreversible, so a careless layout costs fabric and coin. If you can plan a jigsaw, you can play Dressmaker.",
  "",
  "### Where do I get Dressmaker?",
  "",
  "Buy it on **Steam** for Windows and macOS, or try the free prototype at **elyaradine.itch.io/dressmaker**. Both links go to the developers' own pages.",
].join("\n")
  .split('\n').map((line) => resolveFigures(line)).join('\n')
  .replaceAll('@LINK_steam@', LINKS.steam)
  .replaceAll('@LINK_itch@', LINKS.itch);

const FAQ = [
  [
    "Is Dressmaker a real game or just a demo?",
    "Both exist, and they are separate builds. The free prototype on itch.io is a substantial, finished-feeling slice that players have rated 4.8 out of 5. The paid Steam release is the full game, with story commissions, a town of clients, achievements and an ending. Buying the Steam version does not replace the prototype; they are two different downloads."
  ],
  [
    "Is Dressmaker free?",
    "The itch.io prototype is free on a name-your-own-price basis. The full Steam release costs $14.99 in the US, with a 10% launch discount to $13.49. The developers have confirmed there are no microtransactions and no ads."
  ],
  [
    "Is this the same as DressMaker or DressMaker Pro on Steam?",
    "No, and it is worth knowing before you buy the wrong thing. There are two other games on Steam called **DressMaker** and **DressMaker Pro**, both released in 2021, and both are 3D character design tools rather than games. This page is about **Dressmaker** by Cozy Lives and Free Lives, the cozy dressmaking sim that released on September 21, 2026. If the store page you are looking at mentions character rigging or game development, you are on the wrong one.",
    "When did Dressmaker come out?",
    "Dressmaker released on Steam on September 21, 2026 for Windows and macOS. The free prototype has been on itch.io since 2025."
  ],
  [
    "Is Dressmaker on Nintendo Switch, PlayStation or Xbox?",
    "Not yet. The released game is Windows and macOS on Steam, plus the Windows, macOS and Linux prototype on itch.io. In the launch-day Steam announcement the developers said they are planning mobile and Switch ports, so a console version is on the roadmap rather than available today."
  ],
  [
    "Is there a Dressmaker mobile app or a browser version I can play now?",
    "No playable mobile or browser version exists today, and we will not pretend otherwise. The developers did say on launch day that mobile ports are being planned, so expect an official announcement before any real app appears. Any site offering a Dressmaker APK or an online playable version right now is not affiliated with the developers."
  ],
  [
    "How long is Dressmaker?",
    "The developers describe roughly **35 hours of story commissions**, before off-rack dresses, decorating for fun and the post-launch content they have said is still coming."
  ],
  [
    "Is Dressmaker made with AI?",
    "No. The developers have said the game is privately owned and made by hand, and the itch.io prototype carries the **No generative AI was used** tag. Art, code and music are credited to named people."
  ],
  [
    "Is Dressmaker hard?",
    "It is gentle by design — there is no timer and no fail state in the usual sense. The difficulty is that cutting is irreversible, so a careless layout costs fabric and coin. If you can plan a jigsaw, you can play Dressmaker."
  ],
  [
    "Where do I get Dressmaker?",
    "Buy it on **Steam** for Windows and macOS, or try the free prototype at **elyaradine.itch.io/dressmaker**. Both links go to the developers' own pages."
  ]
];

export const page = {
  url: '/',
  title: 'Dressmaker Game: How to Play, Release Date & Tips',
  description: 'Dressmaker is a cozy dressmaking sim out now on Steam. Learn how to play, cut patterns and sew, plus demo download, price, customers and beginner tips.',
  h1: 'Dressmaker Game',
  eyebrow: 'Complete guide',
  lede: "Dressmaker is a cozy dressmaking simulator from developers elyaradine (Jonathan Hau-Yoon), sarandipityx (Sara Laubscher) and raithza (Ruan Rothmann), published by Free Lives under the Cozy Lives label. You run a small dress shop: take a commission, choose the fabric, lay out the pattern, cut it out, sew it together and decorate the finished dress. Then you hand it in and find out whether your customer loves it — or whether you have quietly ruined their wedding.",
  facts: [
    ['Released', 'September 21, 2026'],
    ['Price', '$14.99, or $13.49 at launch'],
    ['Platforms', 'Windows and macOS'],
    ['Free prototype', 'Playable now on itch.io'],
    ['Made by', 'Cozy Lives, published by Free Lives'],
    ['Length', 'About 35 hours of commissions'],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  preload: SHOT_hero,
  crumbs: [{ name: 'Home', url: '/' }],
  schema: [
    {
      '@context': 'https://schema.org',
      '@type': 'VideoGame',
      name: 'Dressmaker',
      alternateName: 'Dressmaker game',
      url: LINKS.steam,
      description: 'Cozy dressmaking simulation game where you choose fabric, cut out patterns, sew garments and decorate them for the townsfolk.',
      genre: ['Simulation', 'Casual', 'Indie'],
      gamePlatform: ['PC (Microsoft Windows)', 'macOS'],
      applicationCategory: 'Game',
      operatingSystem: 'Windows 10 or later, macOS (Apple M1 or later)',
      playMode: 'SinglePlayer',
      datePublished: '2026-09-21',
      author: [
        { '@type': 'Person', name: 'Jonathan Hau-Yoon' },
        { '@type': 'Person', name: 'Sara Laubscher' },
        { '@type': 'Person', name: 'Ruan Rothmann' },
      ],
      publisher: { '@type': 'Organization', name: 'Free Lives' },
      sameAs: [LINKS.steam, LINKS.itch],
    },
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: FAQ.map(([q, a]) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
      })),
    },
  ],
  sources: [
    ['Dressmaker on Steam', LINKS.steam],
    ['Dressmaker prototype on itch.io', LINKS.itch],
    ['Official Steam announcements', LINKS.steamNews],
  ],
  body: BODY,
};
