import { SHOTS, resolveShots } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const BODY = [
  "> Short answer: Dressmaker's public update history runs from the first itch.io prototype patch on **August 4, 2025** to the **September 21, 2026** Steam launch. The prototype numbered its builds 0.4.1 through 0.5.5; **no version number has been published for the Steam build**, and no post-launch patch had appeared on launch day.",
  "",
  "Dressmaker has a longer public paper trail than most cozy games its size. Its first patch note appeared on August 4, 2025, five numbered prototype patches followed within two months, the builds then went quiet for half a year, and the full game reached Steam on September 21, 2026. This page records all of it for the [dressmaker game](/), newest first.",
  "Two caveats. This log is kept by hand by a fan site, not by the developers, and the official [Steam news hub](@LINK_news@) is authoritative — where the two disagree, Steam is right. And as of September 21, 2026 there is no post-launch patch: the only thing Steam carries from launch day is the launch announcement.",
  "## Dressmaker update history at a glance",
  "| Date | Update | Channel | What it did |\n|---|---|---|---|\n| Aug 4, 2025 | Prototype patch | itch.io | Reset Save fixed, gentler sewing |\n| Sep 1, 2025 | Big update | itch.io | Buttons, bows, panel colouring, new character |\n| Sep 2, 2025 | Patch 0.4.1 | itch.io | Scoring and end-of-prototype shop fixes |\n| Sep 3, 2025 | Patch 0.4.2 | itch.io | Fourth-dress blocker fixed, app icon added |\n| Sep 9, 2025 | Hotfix | itch.io | Keyboard sewing controls, scoring rework |\n| Sep 18, 2025 | Prototype update | itch.io | Easier sewing, lace trim, Steam page live |\n| Sep 23, 2025 | Update 0.5.1 | itch.io | Seam allowances, inventory menu, new skirt |\n| Sep 29, 2025 | Hotfix 0.5.3 | itch.io | Ruffle skirt rebuilt, Gothic Collar added |\n| Oct 3, 2025 | Hotfix 0.5.5 | itch.io | Sleeve sprite and ruffle skirt fixes |\n| Nov 11, 2025 | We have gone quiet | itch.io | No patch — prototype builds paused |\n| Apr 15, 2026 | April Tea | Steam | Character measurements, fabric shaders |\n| May 27, 2026 | May Tea | Steam | Fabric inventory rework, off-rack dresses |\n| Jun 9, 2026 | 100k wishlists | Steam | Milestone post, no build changes |\n| Jul 28, 2026 | July Tea | Steam | Launch date set: September 21, 2026 |\n| Aug 31, 2026 | August Tea | Steam | Announced as content complete |\n| Sep 7, 2026 | Scalding September Tea | Steam | $14.99, -10% launch discount |\n| Sep 21, 2026 | Steam launch | Steam | Out now — no patch published yet |",
  "The prototype numbered its own builds, which is where 0.4.1, 0.4.2, 0.5.1, 0.5.3 and 0.5.5 come from. **No version number has been published for the released Steam build**, so none appears here. Updates that shipped without a number are listed by date only.",
  "## Steam release era (April to September 2026)",
  "Everything in this section was announced on the Steam news hub. From April 2026 the same posts were mirrored to the itch.io devlog, often days later; the Steam date is used here.",
  "### September 21, 2026 — Launch day, and no patch yet",
  "Dressmaker is out on Steam for Windows and macOS at **$14.99**, with a **10% launch discount** to **$13.49**. The only post published that day was the launch announcement itself, so there is no patch to report here. It promises small fixes \"in the immediate weeks\" with \"a sprinkling of new fabrics and accessories\", and names what is further off: a challenge mode where players vote on each other's dresses, transparent fabrics, proper controller support, and mobile and Switch ports. Source: the [Steam news hub](@LINK_news@).",
  "### September 7, 2026 — Scalding September Tea: the price, and what is not in the box",
  "Two weeks before launch the developers said the number out loud: **$14.99**, with regional pricing and a **-10% launch discount**. The post also ruled out microtransactions, ads, data harvesting and generative AI, and put figures on the build — roughly **35 hours of story commissions**, **150 dress pieces**, **450 fabrics** and **350 accessories**. Source: the [price announcement on itch.io](@LINK_price@).",
  "### August 31, 2026 — August Tea: content complete, three weeks out",
  "With three weeks to go the team confirmed the date would be met and the game was already content complete: credits compiled, ending finished, achievement icons painted. It is also where the team is named, three full-time developers with almost 40 years of combined experience, plus collaborators on sound, art, testing and music. Source: the [Steam news hub](@LINK_news@).",
  "### July 28, 2026 — July Tea: the launch date arrives",
  "The wishlist count passed **200,000** and the release date was pinned down: **September 21, 2026**. The post opened early-build sign-ups for creators under embargo and showed a brighter, more open front desk. Source: the [July Tea on itch.io](@LINK_july@).",
  "### June 9, 2026 — Dressmaker passes 100,000 wishlists",
  "A milestone post and nothing else. The developers credited prototype players who left detailed comments and screenshots, saying that enthusiasm convinced the people holding the purse strings to greenlight the full game. Source: the [Steam news hub](@LINK_news@).",
  "### June 6, 2026 — Wholesome Direct trailer and a September window",
  "A new trailer dropped during Wholesome Direct, announcing a September 2026 launch window rather than a date. That trailer is the one the Steam store page now lists as the release trailer. Source: the [Steam news hub](@LINK_news@).",
  "### May 27, 2026 — May Tea: a new fabric inventory and off-rack dresses",
  "A fabric inventory rework that shows silk and velvet highlights more accurately, and hides the full fabric name until you hover. The team also described making your own dresses to sell off the rack, and said nine of ten planned characters were illustrated. The itch.io version arrived late, as \"Belated May Tea\" on June 3, 2026. Source: the [Steam news hub](@LINK_news@).",
  "### April 15, 2026 — April Tea: the full game stops looking like the prototype",
  "The first substantial look at the built-from-scratch version. Characters are measured and the mannequin adjusted to fit, with pattern pieces drafted to match. New shaders give silk and velvet different kinds of shine, and the fabric shop was rebuilt to feel like a haberdashery rather than a grid of buttons. The itch.io edition landed on April 17, 2026. Source: the [Steam news hub](@LINK_news@).",
  "## Prototype era: the 2025 patch run",
  "![A green off-the-shoulder dress on a mannequin with the commission completion options](@SHOT_itch@ Hand the dress in, keep working on it, or sell it instead of delivering the commission.)",
  "Everything below is a build update for the free prototype, numbered with its own scheme. The newest files on the [itch.io page](@LINK_itch@) are still labelled 0.5.5, so nothing here has been replaced by a later prototype build.",
  "### November 11, 2025 — \"We've gone quiet!\"",
  "The last post of the prototype era, and there is no patch in it. sarandipityx explained that updates had stopped while the team worked on the full game, and asked readers to wishlist the Steam page. The silence lasted until April 2026. Source: [itch.io devlog](@LINK_devlog@).",
  "### October 3, 2025 — Hotfix 0.5.5",
  "Two fixes: flounce sleeves were showing the three-quarter sleeve sprite in the sketchbook, and the ruffle skirt had the wrong grainline and name. That repair broke panel ordering on skirts players had already made. The team admitted they had been \"a bit messy\" about preserving prototype saves. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 29, 2025 — Hotfix 0.5.3",
  "The busiest patch of the run. Trim placement became less finicky, the mannequin scene gained middle-click zoom, and the ruffle skirt — nicknamed \"the megaskirt\" — was rebuilt with equal side panels, which did break dresses already made with it. It also added needle and pin models, Argyle wool, a new red silk and a Gothic Collar pattern, before a follow-up fixed a save-corruption bug. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 23, 2025 — Update 0.5.1: new content and a long fix list",
  "A new bodice and skirt arrived, with the warning that the skirt \"may genuinely require in the region of about 40m of fabric to cut\". Pattern panels started showing seam allowances, an inventory menu replaced cycling through fabrics, and new trims were added. Fixes covered trim usability, false sewing direction detection, upside-down patterns and a colour picker glitch. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 18, 2025 — The Steam page goes live",
  "The Dressmaker Steam page appeared with wishlisting open, alongside a substantial prototype update. The highlights were, in the developers' words, too many to list: easier sewing, more accessories, more fabrics, one new skirt, and lace trim you could finally add to a finished dress. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 9, 2025 — Hotfix: keyboard controls for sewing",
  "Keyboard controls arrived for sewing, bound to SPACE and the arrow keys, with more consistent mouse sensitivity and a more forgiving sewing line. The patch fixed the newspaper reappearing, pattern panels showing up when switching fabrics, and odd behaviour when interacting with a panel mid-animation. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 5, 2025 — Greenlit, and a sketchbook preview",
  "A small update carrying the year's biggest news. A sketchbook preview now sits beside the cutting room table, and the shop gained new buttons. The developers confirmed Free Lives had greenlit the full game — the numbers were decent, but the passionate comments decided it. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 2 and 3, 2025 — Patches 0.4.1 and 0.4.2",
  "Two patches in two days. The first fixed incorrect scoring, stopped the shop breaking at the end of the prototype, and repaired the butterfly and Juliette sleeves. The second was an emergency fix for a bug that made the fourth dress — the one that needs bows — almost impossible to finish. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 1, 2025 — Big update, and some mixed news",
  "The update that made the prototype worth getting attached to: buttons and bows after sewing, a pageable history of your previous dresses, and panel-by-panel colouring. Sewing was reworked with a speed control, and a new character arrived with two quests. The post also admitted downloads were not yet high enough to make funding an easy yes. Source: [itch.io devlog](@LINK_devlog@).",
  "### August 4, 2025 — The first patch",
  "The oldest post on the devlog, and the first clean-up pass on a prototype built, in the developers' words, in \"a very quick, dirty manner\". Reset Save now actually reset your save, sewing became a little more forgiving, and the confetti audio was made much less jarring. Source: [itch.io devlog](@LINK_devlog@).",
  "## Where the next Dressmaker patch will show up",
  "Patches for the released game appear on the Steam news hub first, and that is the page to follow. The itch.io devlog records the prototype only, and its newest build is still 0.5.5; the developers have not said whether the free prototype will get further updates.",
  "The launch post promises small fixes plus extra fabrics and accessories soon, so this page will be updated as those land. If something breaks in the meantime, the [Dressmaker troubleshooting](/troubleshooting) page covers the common ones. For the launch itself, see [Dressmaker release date](/release-date); for the free prototype, see the [Dressmaker demo](/demo) page.",
].join("\n\n")
  .split('\n').map((line) => resolveShots(line)).join('\n')
  .replaceAll('@LINK_news@', LINKS.steamNews)
  .replaceAll('@LINK_devlog@', LINKS.itchDevlog)
  .replaceAll('@LINK_price@', LINKS.itchPricePost)
  .replaceAll('@LINK_july@', LINKS.itchJulyTea)
  .replaceAll('@LINK_itch@', LINKS.itch);

export const page = {
  url: '/patch-notes',
  title: 'Dressmaker Patch Notes & Update History',
  description: 'Dressmaker patch notes and update history: every prototype hotfix from 0.4.1 to 0.5.5, plus the dated road to the September 2026 Steam launch.',
  h1: 'Dressmaker Patch Notes and Update History',
  eyebrow: "Update history",
  lede: "Dressmaker has a longer public paper trail than most cozy games its size. Its first patch note appeared on August 4, 2025, five numbered prototype patches followed within two months, the builds then went quiet for half a year, and the full game reached Steam on September 21, 2026. This page records all of it for the dressmaker game, newest first.",
  facts: [
    ['First public patch', "August 4, 2025"],
    ['Steam launch', "September 21, 2026"],
    ['Prototype builds', "0.4.1 through 0.5.5"],
    ['Steam build version', "Not published"],
    ['Post-launch patch', "None on launch day"],
    ['Next content', "Fixes, fabrics, accessories, challenge mode"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Patch Notes', url: '/patch-notes' }],
  sources: [
    ['Official Steam announcements', LINKS.steamNews],
    ['Official itch.io devlog', LINKS.itchDevlog],
    ['itch.io prototype page', LINKS.itch],
  ],
  body: BODY,
};