import { SHOTS, resolveShots } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const BODY = [
  "> Short answer: Dressmaker's public update history runs from the first itch.io prototype patch on **August 4, 2025** to the **September 21, 2026** Steam launch. The prototype numbered its builds 0.4.1 through 0.5.5; **no version number has been published for the Steam build**, and no post-launch patch had appeared on launch day.",
  "## How to read this log",
  "Two eras, two channels, two kinds of paperwork.",
  "::: cards\n### itch.io prototype era (2025)\nFree builds, numbered by the developers from 0.4.1 to 0.5.5, each with a devlog post.\n### Steam era (2026)\nThe full game. Updates, milestones and pricing arrive on the Steam news hub first.\n### Version numbers\nOnly the prototype used them. No version number has been published for the released Steam build.\n:::",
  "> Note: the [Steam news hub](@LINK_news@) has no Dressmaker posts before **April 2026**. Everything earlier here comes from the itch.io devlog.",
  "## Update history at a glance",
  "Newest first, for the [dressmaker game](/). Every row is a dated, official post.",
  "| Date | Update | Channel | What changed |\n| --- | --- | --- | --- |\n| Aug 4, 2025 | Prototype patch | itch.io | Reset Save fixed, easier sewing |\n| Sep 1, 2025 | Big update | itch.io | Buttons, bows, panel colouring |\n| Sep 2, 2025 | Patch 0.4.1 | itch.io | Scoring and shop fixes |\n| Sep 3, 2025 | Patch 0.4.2 | itch.io | Fourth-dress blocker fixed |\n| Sep 9, 2025 | Hotfix | itch.io | Keyboard sewing, scoring rework |\n| Sep 18, 2025 | Prototype update | itch.io | Easier sewing, lace trim |\n| Sep 23, 2025 | Update 0.5.1 | itch.io | Seam allowances, inventory menu |\n| Sep 29, 2025 | Hotfix 0.5.3 | itch.io | Ruffle skirt rebuilt |\n| Oct 3, 2025 | Hotfix 0.5.5 | itch.io | Sleeve and skirt fixes |\n| Nov 11, 2025 | We have gone quiet | itch.io | No patch, builds paused |\n| Apr 15, 2026 | April Tea | Steam | Character measurements, shaders |\n| May 27, 2026 | May Tea | Steam | Fabric inventory rework |\n| Jun 6, 2026 | Wholesome Direct | Steam | September 2026 trailer |\n| Jun 9, 2026 | 100k wishlists | Steam | Milestone, no build changes |\n| Jul 28, 2026 | July Tea | Steam | Launch date set |\n| Aug 31, 2026 | August Tea | Steam | Content complete |\n| Sep 7, 2026 | Scalding September Tea | Steam | $14.99, -10% launch discount |\n| Sep 21, 2026 | Steam launch | Steam | Out now, no patch yet |",
  "## Steam era: April to September 2026",
  "Announcements and milestones from April 2026 to launch day, dated by the Steam news hub.",
  "### September 21, 2026 — Launch day, and no patch yet",
  "Out on Windows and macOS at **$14.99**, or **$13.49** at 10% off. The day's only post was the launch announcement: small fixes promised soon, then a challenge mode, transparent fabrics, controller support and mobile and Switch ports. Source: [Steam news hub](@LINK_news@).",
  "### September 7, 2026 — Scalding September Tea: the price",
  "Two weeks out, the developers said the number: **$14.99**, regional pricing, **-10% launch discount**. The post ruled out microtransactions, ads, data harvesting and generative AI, and counted **35 hours** of story commissions, **150 dress pieces**, **450 fabrics** and **350 accessories**. Source: [price announcement on itch.io](@LINK_price@).",
  "### August 31, 2026 — August Tea: content complete",
  "Three weeks from launch: date confirmed, credits compiled, ending finished, achievement icons painted. It also names three full-time developers with almost 40 years of combined experience. Source: [Steam news hub](@LINK_news@).",
  "### July 28, 2026 — July Tea: the launch date",
  "Wishlists passed **200,000** and the date was pinned: **September 21, 2026**. Early-build sign-ups opened for creators under embargo. Source: [July Tea on itch.io](@LINK_july@).",
  "### June 9, 2026 — Dressmaker passes 100,000 wishlists",
  "A milestone post, no build changes. The developers credited prototype players whose comments and screenshots convinced the purse-string holders to greenlight the full game. Source: [Steam news hub](@LINK_news@).",
  "### June 6, 2026 — Wholesome Direct trailer",
  "A trailer in Wholesome Direct announced a September 2026 window, not a date. The Steam store page now lists it as the release trailer. Source: [Steam news hub](@LINK_news@).",
  "### May 27, 2026 — May Tea: fabric inventory and off-rack dresses",
  "A fabric inventory rework that reads silk and velvet highlights more accurately, plus dresses made to sell off the rack. Nine of ten planned characters were illustrated. The itch.io copy came later, as \"Belated May Tea\". Source: [Steam news hub](@LINK_news@).",
  "### April 15, 2026 — April Tea: the full game takes shape",
  "The first substantial look at the built-from-scratch version: measured characters, a mannequin adjusted to fit, and new shaders giving silk and velvet different kinds of shine. The itch.io edition came later, on April 17, 2026. Source: [Steam news hub](@LINK_news@).",
  "## Prototype era: the 2025 build run",
  "Free builds on itch.io, newest first. The newest files on the [itch.io page](@LINK_itch@) are still labelled 0.5.5.",
  "> Note: four prototype updates shipped with no version number — August 4, September 1, September 9 and September 18, 2025.",
  "![A green off-the-shoulder dress on a mannequin with the commission completion options](@SHOT_itch@ Hand the dress in, keep working on it, or sell it instead of delivering the commission.)",
  "### November 11, 2025 — \"We've gone quiet!\"",
  "No patch. sarandipityx said updates had stopped while the team built the full game, and asked readers to wishlist the Steam page. Source: [itch.io devlog](@LINK_devlog@).",
  "### October 3, 2025 — Hotfix 0.5.5",
  "Flounce sleeves showed the wrong sprite, and the ruffle skirt had the wrong grainline and name. The repair broke panel ordering on skirts already made. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 29, 2025 — Hotfix 0.5.3",
  "The busiest patch of the run: less finicky trim placement, middle-click zoom, and the ruffle skirt rebuilt, which broke dresses already made with it. Argyle wool, red silk and a Gothic Collar arrived. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 23, 2025 — Update 0.5.1",
  "A new bodice and skirt, with the warning that the skirt \"may genuinely require in the region of about 40m of fabric\". Seam allowances and an item inventory arrived. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 18, 2025 — The Steam page goes live",
  "Wishlisting opened on a new Steam page, alongside an update too long to list: easier sewing, more accessories, more fabrics, and lace trim for finished dresses. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 9, 2025 — Hotfix: keyboard controls for sewing",
  "Keyboard sewing controls arrived on SPACE and the arrow keys, with a more forgiving sewing line, and the newspaper and panel glitches were fixed. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 5, 2025 — Greenlit, and a sketchbook preview",
  "A sketchbook preview appeared beside the cutting table, and Free Lives confirmed it had greenlit the full game. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 2 and 3, 2025 — Patches 0.4.1 and 0.4.2",
  "Two patches in two days: incorrect scoring and the end-of-prototype shop fixed, then an emergency fix for the fourth dress, the one that needs bows. Source: [itch.io devlog](@LINK_devlog@).",
  "### September 1, 2025 — Big update, and some mixed news",
  "Buttons and bows after sewing, a pageable history of your dresses, panel-by-panel colouring, and a new character with two quests. Source: [itch.io devlog](@LINK_devlog@).",
  "### August 4, 2025 — The first patch",
  "The oldest post on the devlog: Reset Save now reset your save, sewing became more forgiving, and the confetti audio was made less jarring. Source: [itch.io devlog](@LINK_devlog@).",
  "## Where the next patch will show up",
  "Steam news hub first. The itch.io devlog records the prototype only, and its newest build is still 0.5.5.",
  "> Note: no patch for the released Steam build has been published yet. The launch post promises small fixes plus new fabrics and accessories soon.",
  "Something broken? The [Dressmaker troubleshooting](/troubleshooting) page covers the common ones. For the launch itself, see [Dressmaker release date](/release-date); for the free prototype, see the [Dressmaker demo](/demo) page.",
].join("\n\n")
  .split('\n').map((line) => resolveShots(line)).join('\n')
  .replaceAll('@LINK_news@', LINKS.steamNews)
  .replaceAll('@LINK_devlog@', LINKS.itchDevlog)
  .replaceAll('@LINK_price@', LINKS.itchPricePost)
  .replaceAll('@LINK_july@', LINKS.itchJulyTea)
  .replaceAll('@LINK_itch@', LINKS.itch);

export const page = {
  url: '/patch-notes',
  title: 'Dressmaker Patch Notes & Update History',
  description: 'Dressmaker patch notes and update history: every prototype hotfix from 0.4.1 to 0.5.5, plus the dated road to the September 2026 Steam launch.',
  h1: 'Dressmaker Patch Notes and Update History',
  eyebrow: "Update history",
  lede: "Dressmaker has a longer public paper trail than most cozy games its size. Its first patch note appeared on August 4, 2025, five numbered prototype patches followed within two months, the builds then went quiet for half a year, and the full game reached Steam on September 21, 2026. This page records all of it for the dressmaker game, newest first.",
  facts: [
    ['First public patch', "August 4, 2025"],
    ['Steam launch', "September 21, 2026"],
    ['Prototype builds', "0.4.1 through 0.5.5"],
    ['Steam build version', "Not published"],
    ['Post-launch patch', "None on launch day"],
    ['Next content', "Fixes, fabrics, accessories, challenge mode"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Patch Notes', url: '/patch-notes' }],
  sources: [
    ['Official Steam announcements', LINKS.steamNews],
    ['Official itch.io devlog', LINKS.itchDevlog],
    ['itch.io prototype page', LINKS.itch],
  ],
  body: BODY,
};
