import { LINKS } from '../data/site.mjs';

const BODY = [
"This policy explains what data dressmakerguide.com collects, why, and what you can do about it. It is written to be read, not to be survived. Last updated **September 21, 2026**.",
"",
"## The short version",
"",
"- We do not ask you to create an account, and there is nothing to log in to.",
"- We do not sell your personal information, and we do not run a mailing list.",
"- The site itself is a set of static pages. It does not set cookies of its own.",
"- Third parties we may use - advertising (Google AdSense) and analytics (Google Analytics) - do set cookies and process data such as your IP address and approximate location. Details below.",
"",
"## Who we are",
"",
"dressmakerguide.com is an independent fan site about the game Dressmaker. For any privacy question, use the [contact page](/contact). We are the data controller for the limited data described here.",
"",
"## What is collected and why",
"",
"### Server and hosting logs",
"",
"Our host records standard request data: IP address, user agent, the URL requested and a timestamp. This is used for security, abuse prevention and basic traffic measurement. It is retained for a short period by the hosting provider and is not combined with any other data by us.",
"",
"### Analytics",
"",
"If analytics is enabled, we use Google Analytics 4 to understand which pages are useful. It records page views, approximate location derived from IP address, device and browser type, and how you arrived at the site. Google Analytics 4 does not log or store full IP addresses for European Economic Area users. We use this only in aggregate: to see which pages people read, and which ones they bounce off.",
"",
"### Advertising",
"",
"This site is supported by advertising, and we use **Google AdSense** to serve it.",
"",
"- Third-party vendors, including Google, use cookies to serve ads based on your prior visits to this and other websites.",
"- Google's use of advertising cookies enables it and its partners to serve ads to you based on your visit to this site and/or other sites on the internet.",
"- You can opt out of personalised advertising by visiting [Google Ads Settings](https://adssettings.google.com/).",
"- You can also opt out of third-party vendor cookies for personalised advertising at [aboutads.info](https://www.aboutads.info/choices/) or [youronlinechoices.eu](https://www.youronlinechoices.eu/) in the EU.",
"- For more information about how Google uses data when you use partner sites, see [Google's partner sites policy](https://policies.google.com/technologies/partner-sites).",
"",
"Where required by law, we ask for consent before advertising or analytics cookies are set, and you can refuse without losing access to any content on this site. Every page here works with all cookies blocked.",
"",
"### Contact messages",
"",
"If you email us, we receive your address and whatever you write. We keep it only as long as it takes to answer you and fix whatever you reported, then delete it. We do not add you to a list.",
"",
"## Your rights",
"",
"Depending on where you live, you may have the right to access, correct or delete personal data we hold, to object to processing, to withdraw consent, and to lodge a complaint with your local data protection authority.",
"",
"- **EEA, UK and Switzerland (GDPR / UK GDPR):** you have the rights listed above. Because we hold almost nothing directly, most requests will relate to Google's processing, which you exercise through the links in the advertising section.",
"- **California (CCPA / CPRA):** we do not sell or share personal information as those terms are defined by the CPRA, and we do not knowingly collect information from consumers under 16.",
"- **Everyone:** you can email us through the [contact page](/contact) and we will respond within 30 days.",
"",
"## Children",
"",
"This site is not directed at children under 13, and we do not knowingly collect personal information from them. Dressmaker is rated for a general audience and our guides are written for adults and older teenagers who play it.",
"",
"## Third-party links",
"",
"Pages here link out to Steam, itch.io, YouTube, Discord and press sites. Once you leave this site, their privacy policies apply, not ours. We have no control over what they collect.",
"",
"## Data retention and security",
"",
"We keep server logs only as long as the host retains them, and contact emails only as long as needed. There is no user database to breach, because there is no user database at all. We serve the site over HTTPS and set conservative security headers.",
"",
"## Changes to this policy",
"",
"If this policy changes in a way that matters - a new advertising partner, a new analytics tool - we will update the date at the top and describe the change in the [patch notes](/patch-notes) style log on the about page.",
"",
"## One more time, in plain English",
"",
"Read the guides. Block the cookies if you like. Nothing on this site breaks, and we will never know.",
].join("\n");

export const page = {
  url: '/privacy',
  title: 'Privacy Policy | Dressmaker Guide',
  description: 'How dressmakerguide.com handles data: hosting logs, Google Analytics, AdSense advertising cookies, your GDPR and CCPA rights, and how to opt out.',
  h1: 'Privacy Policy',
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Privacy', url: '/privacy' }],
  body: BODY,
};
