import { SHOTS, resolveShots } from '../data/images.mjs';
import { SITE, LINKS } from '../data/site.mjs';

const SHOT_cut = SHOTS.cut.src;
const SHOT_decorate = SHOTS.decorate.src;
const LINK_steam = LINKS.steam;

const BODY = [
  "> Short answer: Four decisions decide most dresses: match the grain unless a bias cut is deliberate, keep large prints off small panels, preview the layout on the mannequin, and learn on cheap cloth. Trim rescues a plain dress, never a badly cut one.",
  "",
  "New to the [dressmaker game](/)? Start with [how to play Dressmaker](/how-to-play).",
  "",
  "## Quick answers",
  "",
  "Every tip here, in one line.",
  "",
  "| Question | Short answer |",
  "| --- | --- |",
  "| Align to the grain or cut on the bias? | Align by default |",
  "| When is a bias cut worth it? | Simple shape, fluid cloth |",
  "| Big print on a small panel? | Move it to a bigger piece |",
  "| One fabric for the whole dress? | One drape per dress |",
  "| What order do I sew in? | Flat first, sleeves before hems |",
  "| The dress looks wrong? | Run the fix list below |",
  "",
  "## Grain and bias",
  "",
  "Lengthwise grain runs parallel to the selvedge and stretches least. Align to it by default.",
  "",
  "| Cut | What it does | Use it when |",
  "| --- | --- | --- |",
  "| On grain | Hangs square, keeps its seams | Bodices, waistbands, straight skirts |",
  "| On the bias | Stretches, ripples, drapes | Fluid cloth, no stripes or plaid |",
  "",
  "The [official Steam description](@LINK_steam@) says your arrangement and your cut are what show on the final dress.",
  "",
  "> Warning: bias beside straight grain behaves like a different cloth at the seam.",
  "",
  "## Print scale vs pattern piece size",
  "",
  "If the repeat is wider than the piece, that piece captures a fragment — one petal, half a stem.",
  "",
  "- **Stripes must meet at the seam.** A band that steps up by a fraction is obvious.",
  "- **Plaid matches two ways**, so place pieces to suit the repeat.",
  "- **Mirrored pieces make a chevron.** Good at a center back seam, a mistake at a side.",
  "",
  "> Tip: give a panel one full repeat, and save the big floral for the skirt.",
  "",
  "## Fabric, panel by panel",
  "",
  "A crisp bodice over a fluid skirt is a choice; mixed drape is an accident.",
  "",
  "| Fabric | Behaves like | Best for | Watch out for |",
  "| --- | --- | --- | --- |",
  "| Cotton | Holds a line, easy to handle | Everyday dresses, bodices | Flat on a full skirt |",
  "| Linen | Crisp, visible weave | Summer dresses | Fights a busy print |",
  "| Wool | Dense, hangs heavy | Tailored winter skirts | Rigid under a soft shape |",
  "| Silk | Fluid, holds nothing | Bias cuts, soft skirts | Shows every pucker |",
  "| Velvet | Deep color, adds weight | Statement dresses | Reverse cuts read as two colors |",
  "",
  "> Note: in-game fabric stats are not published. The mannequin is your measurement.",
  "",
  "## Layout before you cut",
  "",
  "![Paper pattern pieces laid out on strawberry-print fabric with shears resting on the cloth](@SHOT_cut@ Pattern pieces on the cloth decide what the dress looks like. The shears decide it permanently.)",
  "",
  "Nothing later repairs a bad layout, so plan the whole table first.",
  "",
  "::: steps",
  "1. **Tile the big pieces first** — skirt, back and sleeves.",
  "2. **Fit small pieces into gaps** — what the big pieces leave.",
  "3. **Decide what you optimize for** — minimum waste and a matched repeat differ.",
  "4. **Keep direction consistent** — prints and naps face one way.",
  "5. **Stay off the selvedge** — it prints a different shade.",
  "6. **Keep every offcut** — the cheapest practice cloth you will get.",
  ":::",
  "",
  "> Tip: preview every layout on the mannequin. It is the last free check.",
  "",
  "> Warning: cutting is permanent. The fabric is spent when the shears go through it.",
  "",
  "## Seam order",
  "",
  "Sew in an order that keeps the fiddly work flat.",
  "",
  "::: steps",
  "1. **Build small pieces into big ones** — while everything is flat.",
  "2. **Close the shoulders and side seams** — two panels become a tube.",
  "3. **Set the sleeves while the body is open** — easier than a finished dress.",
  "4. **Finish hems and openings last** — the edges you handle most.",
  ":::",
  "",
  "> Tip: place buttons, bows and appliqué flat on the table. The machine's bobbin never runs out.",
  "",
  "## Decoration discipline",
  "",
  "![A finished strawberry-print dress on a mannequin beside a tray of accessories](@SHOT_decorate@ Sewing finished, decorating not: buttons, bows and lace can still be added.)",
  "",
  "Trim frames a good cut or points at a bad one. It never hides a broken print.",
  "",
  "::: cards",
  "### One focal point per dress",
  "Busy fabric wants quiet trim; plain fabric carries a statement.",
  "### Match the trim to the occasion",
  "Lace and heavy appliqué for formal work; everyday dresses want restraint.",
  "### Clutter is the easiest mistake",
  "Three trims fighting for attention read as noise.",
  ":::",
  "",
  "The full game has over 350 accessories, so restraint is worth learning.",
  "",
  "## Read the customer before you sew",
  "",
  "Designing before you know the occasion, the taste and the numbers wastes a bolt.",
  "",
  "::: steps",
  "1. **Read the occasion** — a wedding and a market stall differ.",
  "2. **Read the taste** — what this client likes, in her own words.",
  "3. **Read the numbers** — the sketchbook lists attribute targets; one screenshot reads **Quality 70, Flowers 60, Cute 30, Romantic 45**.",
  "4. **Design in the sketchbook** — from what your shop stocks.",
  ":::",
  "",
  "Hand-in pays **coin** and **reputation**; the customer card shows a **star rating**.",
  "",
  "> Note: how the stars are calculated has never been published.",
  "",
  "See [Dressmaker customer preferences](/customers) for reading a brief, and missing on purpose.",
  "",
  "## Coin, reputation and which bolt to spend",
  "",
  "| Cloth you buy | What it buys you |",
  "| --- | --- |",
  "| Cheap cotton | Practice at layout and seam order |",
  "| An expensive bolt for a paying commission | A dress the customer remembers |",
  "| A dress sold off the rack | Steady coin, nobody's wedding on it |",
  "",
  "Coin buys the next bolt; reputation is what the town remembers.",
  "",
  "> Tip: while you are learning, buy the cheapest cloth that fits the brief.",
  "",
  "> Note: fabric prices, coin amounts and reputation thresholds are not published.",
  "",
  "## Fix a dress that looks wrong",
  "",
  "Check these before you blame the sewing.",
  "",
  "| What you see | Likely cause | What to do |",
  "| --- | --- | --- |",
  "| Silhouette sags or stands away | Cloth fighting the shape | Change the bolt, not the pattern |",
  "| Print looks broken | Repeat bigger than the panel | Cut it from a bigger piece |",
  "| Stripes step at a seam | Layout fault | Nothing fixes it after cutting |",
  "| One panel a different color | Nap, on velvet | Cut every panel the same way |",
  "| The hem waves | Bias beside straight grain | Re-cut, or even it out |",
  "| It looks fussy | Too much trim | Take one trim off |",
  "| The dress is fine, the customer is not | You missed the occasion | Re-read the brief; [customer preferences](/customers) covers it |",
  "",
  "Dressmaker rewards workroom habits: plan the cut, respect the grain, spend cloth where it shows. The [Dressmaker wiki](/wiki) holds the reference tables, the [dressmaker game](/) homepage covers the release and the free prototype, and [games like Dressmaker](/games-like) is next.",
].join("\n")
  .split('\n').map((line) => resolveShots(line)).join('\n')
  .replaceAll('@LINK_steam@', LINK_steam);

export const page = {
  url: '/sewing-tips',
  title: "Dressmaker Guide: Sewing Tips for Better Dresses",
  description: "Dressmaker guide: how grain, bias, print scale and fabric choice decide every panel you cut, plus seam order, trim discipline and a fix-it list.",
  h1: 'Dressmaker Guide: Sewing Tips and Pattern Advice',
  eyebrow: "Guide",
  lede: "Most dresses in Dressmaker are lost before the sewing machine is switched on. Where each pattern piece lands on the cloth, and which way the grain runs through it, is what your customer sees at the end.",
  facts: [
    ['Grain first', "Align unless a bias cut is deliberate"],
    ['Prints', "Keep large repeats off small panels"],
    ['Before cutting', "Preview every layout on the mannequin"],
    ['Seam order', "Assemble flat before you close the garment"],
    ['Spending', "Cheap cloth while you are still learning"],
    ['Trim', "Rescues a plain dress, never a bad cut"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  preload: SHOT_cut,
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Sewing Tips', url: '/sewing-tips' }],
  schema: [
    {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Dressmaker Guide: Sewing Tips and Pattern Advice',
      description: "Dressmaker guide: how grain, bias, print scale and fabric choice decide every panel you cut, plus seam order, trim discipline and a fix-it list.",
      inLanguage: 'en-US',
      datePublished: '2026-09-21',
      dateModified: '2026-09-21',
      mainEntityOfPage: SITE.origin + '/sewing-tips/',
      author: { '@type': 'Organization', name: SITE.name },
      publisher: { '@type': 'Organization', name: SITE.name },
    },
  ],
  sources: [
    ['Dressmaker on Steam (grain and bias wording)', LINKS.steam],
    ['Official itch.io devlog', LINKS.itchDevlog],
  ],
  body: BODY,
};