import { SHOTS, resolveShots } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const BODY = [
  "> Short answer: Dressmaker problems are usually one of five things: an out-of-date GPU driver, the macOS Gatekeeper warning on the un-notarized itch.io prototype, a partial download, a laptop throttling, or a blocked network.",
  "",
  "The two builds need different fixes — see the [dressmaker game](/) home page.",
  "",
  "## Find your problem",
  "",
  "| Symptom | Most likely cause | Section |",
  "| --- | --- | --- |",
  "| Play does nothing | Driver or Steam files | [Won't start](#1-will-not-start-on-windows) |",
  "| Runs, but stutters | Overlays and heat | [Stutter](#2-stuttering-or-a-low-frame-rate) |",
  "| macOS calls it malicious | Not notarized | [macOS warning](#3-the-macos-warning) |",
  "| The zip will not open | Partial download | [Bad zip](#4-the-itchio-zip) |",
  "| itch.io never loads | VPN or network | [itch.io down](#5-itchio-will-not-load) |",
  "| Worried about progress | Cloud files unpublished | [Saves](#6-saves-and-steam-cloud) |",
  "| Wrong fabric cut | No undo | [Wrong cut](#7-you-cut-the-wrong-fabric) |",
  "| Crash or broken commission | A bug to report | [Bug report](#8-reporting-a-bug) |",
  "",
  "> Tip: verifying the game files and updating your GPU driver clear most reports. Try both first.",
  "",
  "## 1. Will not start on Windows",
  "",
  "You press Play, Steam says running, and nothing appears.",
  "",
  "::: steps",
  "1. **Verify the game files** — Steam → right-click Dressmaker → Properties → Installed Files → Verify integrity.",
  "2. **Update your GPU driver** — from Intel, AMD or NVIDIA, not Windows Update. UHD 630 and DirectX 11 are the minimum.",
  "3. **Run as administrator** — right-click → Manage → Browse local files → Properties → Compatibility.",
  "4. **Check Windows 10 or later** — Settings → System → About. Older versions are unsupported.",
  "5. **Check antivirus quarantine** — restore the game's files, then exclude your Steam library.",
  "6. **Try the publicbeta branch last** — SteamDB lists one as “Experimental and untested changes”.",
  ":::",
  "",
  "## 2. Stuttering or a low frame rate",
  "",
  "| Fix | Why it works |",
  "| --- | --- |",
  "| Close browsers, launchers and overlays | They fight the game for the same GPU |",
  "| Install fresh GPU drivers | Fresh drivers matter more than raw power |",
  "| Go windowed, drop a resolution step | The game still looks fine |",
  "| Use a hard surface and clear the vents | A laptop that crawls after ten minutes is hot, not slow |",
  "| Check the published minimum | 8 GB RAM and an i5 or Ryzen; Apple M1 on Mac |",
  "",
  "No recommended tier is published: [Dressmaker system requirements](/system-requirements).",
  "",
  "## 3. The macOS warning",
  "",
  "The itch.io prototype is not notarized, so macOS blocks it as unverified.",
  "",
  "::: steps",
  "1. **Open System Settings** — then Privacy & Security.",
  "2. **Click Open Anyway** — in the security section.",
  "3. **Confirm the second prompt** — the prototype opens.",
  ":::",
  "",
  "> Tip: that button appears only after macOS blocks the app once, so try opening the game first.",
  "",
  "> Note: the Steam release installs normally; if it will not open, verify the files in Steam.",
  "",
  "## 4. The itch.io zip",
  "",
  "| File (version 0.5.5) | Platform | Size |",
  "| --- | --- | --- |",
  "| Dressmaker Prototype Windows 0.5.5.zip | Windows | 115 MB |",
  "| Dressmaker Prototype Linux 0.5.5.zip | Linux | 127 MB |",
  "| Dressmaker Prototype OSX 0.5.5.zip | macOS | 128 MB |",
  "",
  "| Fix | Why it works |",
  "| --- | --- |",
  "| Download it again | A partial file is much smaller than the listed size |",
  "| Open it with 7-Zip or The Unarchiver | Explorer and Archive Utility fail on big downloads |",
  "| Clear a couple of gigabytes | Unzipping needs that much space again |",
  "| Retry later or on another network | A crawling download is itch.io or your ISP |",
  "",
  "## 5. itch.io will not load",
  "",
  "- **Try a second browser** — then a private window, extensions off.",
  "- **Turn off your VPN and try another network** — a hotspot rules out your connection.",
  "- **School and office networks block game sites.**",
  "",
  "Direct download: [Dressmaker demo](/demo).",
  "",
  "## 6. Saves and Steam Cloud",
  "",
  "Steam Cloud is listed, so progress should follow your account.",
  "",
  "| Question | Honest answer |",
  "| --- | --- |",
  "| Cloud supported? | Yes, it is listed |",
  "| Which files sync? | Unpublished |",
  "| Where is the save folder? | Unverified; we will not invent a path |",
  "| How do I find it? | Right-click Dressmaker → Manage → Browse local files; per-game data also sits under userdata, your account ID, App ID 4019220 |",
  "",
  "> Warning: no save path is verified, and reinstalling can overwrite progress. Copy the whole folder first.",
  "",
  "## 7. You cut the wrong fabric",
  "",
  "![Paper pattern pieces laid out on strawberry-print fabric with shears resting on the cloth](@SHOT_cut@ Pattern pieces laid on the cloth decide what the dress will look like. Then the shears decide it permanently.)",
  "",
  "There is no undo: the cut is what shows on the finished dress.",
  "",
  "- **Preview on the mannequin** — the last free check before every cut.",
  "- **Practice on cheap cotton** — learn the layout before you buy velvet.",
  "",
  "> Warning: cutting is permanent. Fabric is spent the moment the shears go through it.",
  "",
  "More layout advice: [Dressmaker sewing tips](/sewing-tips).",
  "",
  "## 8. Reporting a bug",
  "",
  "Report it in the [Dressmaker Steam discussions](@LINK_discussions@) or the developers' Discord (invite on the [itch.io page](@LINK_itch@)).",
  "",
  "- **Your build** — Steam branch or prototype file name.",
  "- **Platform and hardware** — OS and graphics card.",
  "- **Steps to reproduce, and what happened instead.**",
  "- **A screenshot, plus your save file if progress is involved.**",
  "",
  "## When to report it",
  "",
  "Work down this ladder and stop when the problem is solved.",
  "",
  "::: steps",
  "1. **Restart Steam and verify the game files.**",
  "2. **Update your OS and graphics driver.**",
  "3. **Work through the matching section above.**",
  "4. **Check the [Dressmaker patch notes](/patch-notes)** — a hotfix may be out.",
  "5. **Report it** — Steam discussions or Discord.",
  "6. **Still stuck?** — [tell us](/contact).",
  ":::",
  "",
  "## Frequently asked questions",
  "",
  "### Does Dressmaker support Steam Cloud?",
  "",
  "Yes, it is listed among the game's Steam features, but the developers have not published which files sync. Keep your own copy of anything you would hate to lose.",
  "",
  "### Can I undo a cut in Dressmaker?",
  "",
  "No. Cutting is irreversible by design. Practice on cheap cotton and preview on the mannequin first.",
  "",
  "### Why does macOS say the prototype may be malicious?",
  "",
  "Because it is not notarized, so macOS cannot verify the developer. The fix is System Settings, Privacy & Security, then Open Anyway.",
  "",
  "### Where do I report a Dressmaker bug?",
  "",
  "In the official Steam discussions or the developers' Discord, with your build, platform, exact steps and a screenshot.",
  "",
  "### Why will my antivirus not let Dressmaker run?",
  "",
  "Heuristic scanners sometimes quarantine files from small studios. Check your protection history, restore them and exclude your Steam library.",
].join("\n")
  .split('\n').map((line) => resolveShots(line)).join('\n')
  .replaceAll('@LINK_discussions@', LINKS.steamDiscussions)
  .replaceAll('@LINK_itch@', LINKS.itch);

const FAQ = [
  [
    "Does Dressmaker support Steam Cloud?",
    "Yes, Steam Cloud is listed among the game's Steam features. The developers have not published which files sync, so treat it as a safety net rather than a backup and keep your own copy of anything you would hate to lose."
  ],
  [
    "Can I undo a cut in Dressmaker?",
    "No. Cutting is irreversible by design and there is no undo. Practice on cheap cotton and check the mannequin preview before every cut."
  ],
  [
    "Why does macOS say the prototype may be malicious?",
    "Because the itch.io prototype is not notarized, so macOS cannot verify the developer. The official fix is System Settings, Privacy & Security, then Open Anyway."
  ],
  [
    "Where do I report a Dressmaker bug?",
    "In the official Steam discussions or the developers' Discord, with your build, platform, exact steps and a screenshot."
  ],
  [
    "Why will my antivirus not let Dressmaker run?",
    "Heuristic scanners sometimes quarantine files from small studios. Check your protection history, restore anything belonging to the game and exclude your Steam library."
  ],
];

export const page = {
  url: '/troubleshooting',
  title: 'Dressmaker Troubleshooting: Common Fixes',
  description: 'Dressmaker troubleshooting for PC and Mac: launch failures, stutter, the macOS warning, failed itch.io downloads, saves and where to report a bug.',
  h1: 'Dressmaker Troubleshooting',
  eyebrow: "Fixes",
  lede: "Dressmaker is a small, well-behaved game, so when something breaks it is usually Steam, a driver, macOS Gatekeeper or your network.",
  facts: [
    ['Most common', "Out-of-date GPU drivers"],
    ['macOS', "Gatekeeper blocks the itch.io prototype"],
    ['Stutter', "Background apps, drivers, thermals"],
    ['itch.io', "Zips are 115–128 MB, check the download"],
    ['Saves', "Steam Cloud is listed; back up anyway"],
    ['Bugs', "Official Steam discussions"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  preload: SHOTS.cut.src,
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Troubleshooting', url: '/troubleshooting' }],
  schema: [
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: FAQ.map(([q, a]) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
      })),
    },
  ],
  sources: [
    ['Dressmaker Steam discussions', LINKS.steamDiscussions],
    ['itch.io prototype page (macOS warning, Discord)', LINKS.itch],
    ['Dressmaker on Steam (published requirements)', LINKS.steam],
  ],
  body: BODY,
};
