import { SHOTS, resolveShots } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const BODY = [
  "> Short answer: This wiki collects what is actually documented about Dressmaker: fabric families and how they behave, the pattern pieces a dress is assembled from, the decoration types, the order of the making loop, and a plain-English glossary. In-game numbers the developers have not published — per-bolt prices, unlock order, the full attribute list — are marked as unpublished rather than guessed.",
  "",
  "This is the reference layer for the [dressmaker game](/) — the tables to keep open in a second tab. Dressmaker is a cozy dressmaking simulation from elyaradine, sarandipityx and raithza, published by **Free Lives** and out on Steam since **September 21, 2026** for Windows and macOS.",
  "",
  "Everything here comes from what the developers published themselves: the official [Steam store page](@LINK_steam@) and their own [itch.io devlog](@LINK_devlog@). Where a number is not published, this page says so instead of guessing.",
  "",
  "## Materials at a glance",
  "",
  "The store page names five fabrics outright — cotton, linen, wool, silk and velvet — then promises 'a wide range of fabrics', which the developers counted at **over 450** for launch. No per-fabric stats or prices are published, so these notes describe how each family behaves in real dressmaking — the vocabulary the game is built on.",
  "",
  "| Fabric | What it does well (drape, warmth, structure, shine) | Best suited to | Watch out for |",
  "|---|---|---|---|",
  "| Cotton | Soft even drape, matte finish, holds a shape | Everyday commissions, fitted bodices, first attempts | Creases; looks flat beside silk or velvet; buttons vanish on prints |",
  "| Linen | Cool, dry handle and a visible weave | Summer dresses, relaxed skirts where the cloth is the decoration | The loud weave swallows fine lace; creases at every fold |",
  "| Wool | Warm, matte and structured — holds a tailored line | Cold-weather commissions, tailored bodices, heavier skirts | Bulk builds at seams and hems; swallows light trims |",
  "| Silk | High shine, fluid drape, almost no weight | Evening and wedding commissions, bias-cut panels, gowns | Off-centre panels show in the light; slippery to lay out |",
  "| Velvet | Deep colour, light-absorbing pile, instant drama | One statement piece, such as a bodice against a matte skirt | The pile has a direction, so panels cut opposing ways read as different shades |",
  "| Specialty / printed fabrics | Everything else on the shelf | Prints, novelty cloth, dresses where the print is the point | No per-bolt stats or unlock order published; judge these by family |",
  "",
  "### Where this table stops being useful",
  "",
  "That last row is a family, not a bolt: we can tell you how cotton behaves, not that bolt 217 runs heavy. Shop by weight, by drape and by whether the print has a direction.",
  "",
  "## Pattern pieces and garment panels",
  "",
  "A dress here is not an item you pick off a menu. It is assembled from pattern pieces you arrange on cloth, cut out and sew together, and the store page is explicit that 'how you choose to arrange and cut out your fabric is what appears on the final dress' — you 'take full control over what fabric to use for each panel.' Two words decide the result. **Grain** is the direction the threads run in the cloth; align a piece with it and the panel hangs straight. **Bias** means cutting diagonally across that line, which makes the same cloth drape softer.",
  "",
  "![Paper pattern pieces laid out on strawberry-print fabric with shears resting on the cloth](@SHOT_cut@ Pattern pieces laid on the cloth decide what the dress will look like. Then the shears decide it permanently.)",
  "",
  "| Garment area | What it decides | What to consider |",
  "|---|---|---|",
  "| Bodice | The panel closest to your customer's face, and the most pieces | Fine prints survive here; align the centre front to the grain; contrast fabric reads best |",
  "| Sleeves | A mirrored pair, cut twice as opposites | Directional prints flip on the second sleeve; plainer cloth lets the bodice lead |",
  "| Skirt | The largest pieces, so the most cloth and the most print on show | The home for a statement fabric; grain hangs evenly, bias is dramatic |",
  "| Trim and finishing | Bands, edgings and decoration on the finished garment | Judge a trim against the panel it sits on — lace over velvet disappears |",
  "",
  "The [how to play Dressmaker](/how-to-play) walkthrough takes these same stages in order, and the [sewing tips](/sewing-tips) page goes deeper on layout and seam order.",
  "",
  "## Decorations: buttons, bows, appliqué and lace",
  "",
  "The store page names four decoration types: **buttons, bows, appliqué and lace trims**, placed 'wherever you like with complete creative freedom', from **over 350 accessories** in the launch build. Appliqué is the odd one: you plan it in the sketchbook, so it is a design choice and a decoration at once.",
  "",
  "| Decoration | What it is for | Where it reads best |",
  "|---|---|---|",
  "| Buttons | Small, repeated, precise — a row is rhythm, not a focal point | Centre fronts, cuffs and bodice openings, where the spacing shows |",
  "| Bows | One soft, rounded shape that pulls the eye to a single point | Waistlines, shoulders, the back, a neckline — scaled to the commission |",
  "| Appliqué | Shaped fabric placed on the surface as a design element | Motifs on a skirt or shapes across a bodice, in a contrasting tone |",
  "| Lace trim | Edging for borders, hems, necklines and seams — a linear decoration | Any line that wants following: a hem, a cuff, a panel boundary |",
  "",
  "## The loop, in reference form",
  "",
  "Six stages, in the order the game asks for them. Dressmaker runs on two currencies, **coin and reputation**, and not one in-game price has been published. Where a cost is unknown, the table says so.",
  "",
  "| Stage | What you do | What it costs |",
  "|---|---|---|",
  "| 1. Design in the sketchbook | Choose a silhouette, colour it, add fabric samples and appliqué | Nothing but time — designing is planning, not spending |",
  "| 2. Buy fabric | Buy from the shelves; over 450 fabrics ship with the game | Coin. Per-fabric prices are not published. |",
  "| 3. Arrange and cut | Lay the pieces out on the cloth, check the mannequin, then cut | The cloth itself. Cutting is irreversible; the preview is your only undo. |",
  "| 4. Sew the panels | Feed the fabric through the sewing machine | Nothing to manage — the machine has an infinite bobbin |",
  "| 5. Decorate | Add buttons, bows, appliqué, lace trims and accessories | Not published. We will not guess whether accessories cost coin. |",
  "| 6. Hand in or sell off the rack | Turn the dress in, or sell pre-made dresses from your shop window | Nothing up front — this is where coin and reputation come back |",
  "",
  "The loop we can verify is that handing in dresses earns coin and reputation. What reputation unlocks, and in what order, has not been published, so treat any tier list you find elsewhere with suspicion. The [customer preferences](/customers) page covers reading the brief.",
  "",
  "## Key terms",
  "",
  "Standard dressmaking words, in plain English — the same terms the game uses in its interface.",
  "",
  "| Term | What it means |",
  "|---|---|",
  "| Grain | The direction the threads run in a woven fabric; aligning a pattern piece with it is the predictable cut. |",
  "| Bias | Cutting diagonally across the grain, so a panel drapes differently. An effect, not a default. |",
  "| Panel | One piece of a garment — bodice, sleeve, skirt, trim — before it is sewn to its neighbours. You choose its fabric. |",
  "| Appliqué | A shaped piece of fabric stitched onto another to make a design. Named in the sketchbook and in the decoration list. |",
  "| Off the rack | Ready-made rather than made to measure: the pre-made dresses you display and sell. |",
  "| Mannequin | The display figure that previews a garment before you cut, and how finished dresses look in the window. |",
  "| Notions | The trade word for small sewing supplies — buttons, trims, thread — as opposed to the cloth. |",
  "",
  "## What this wiki is, and what it is not",
  "",
  "Two honest limits. This is a **fan-made reference**, not an official one: every claim traces back to the official Steam store page or the developers' own itch.io devlog. And in-game numbers are not published — prices, unlock order, per-fabric stats and accessory costs have never been released, so any wiki quoting an exact coin price during launch week is guessing.",
  "",
  "If something here is wrong or out of date, [tell us](/contact). If you would rather play than read, start with [how to play Dressmaker](/how-to-play), sharpen your technique on the [sewing tips](/sewing-tips) page, and check your machine against the [system requirements](/system-requirements).",
].join("\n")
  .split('\n').map((line) => resolveShots(line)).join('\n')
  .replaceAll('@LINK_steam@', LINKS.steam)
  .replaceAll('@LINK_devlog@', LINKS.itchDevlog);

export const page = {
  url: '/wiki',
  title: 'Dressmaker Wiki: Fabrics, Patterns & Accessories',
  description: 'A fan-made Dressmaker wiki built from the official store page and devlog: fabric families, pattern pieces, decorations, the making loop and a glossary.',
  h1: 'Dressmaker Wiki',
  eyebrow: "Reference",
  lede: "This is the reference layer for the dressmaker game — the tables to keep open in a second tab. Dressmaker is a cozy dressmaking simulation from elyaradine, sarandipityx and raithza, published by Free Lives and out on Steam since September 21, 2026 for Windows and macOS.",
  facts: [
    ['Fabric families', "Cotton, linen, wool, silk, velvet"],
    ['Launch content', "450+ fabrics, 150+ dress pieces"],
    ['Accessories', "350+ across buttons, bows, appliqué, lace"],
    ['Assembly', "Pattern pieces arranged on cloth by hand"],
    ['Decoration', "Placed freely after sewing"],
    ['Not published', "Per-bolt stats, prices, unlock order"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Wiki', url: '/wiki' }],
  schema: [
    {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Dressmaker Wiki: Fabrics, Patterns & Accessories',
      description: 'Reference tables for Dressmaker: fabric families, pattern pieces and panels, decoration types, the six-stage making loop and a glossary of dressmaking terms.',
      datePublished: '2026-09-21',
      dateModified: '2026-09-21',
      inLanguage: 'en-US',
      author: { '@type': 'Organization', name: 'Dressmaker Guide' },
      about: {
        '@type': 'VideoGame',
        name: 'Dressmaker',
        url: LINKS.steam,
        genre: ['Simulation', 'Casual', 'Indie'],
        gamePlatform: ['PC (Microsoft Windows)', 'macOS'],
        datePublished: '2026-09-21',
      },
      isPartOf: { '@type': 'WebSite', name: 'Dressmaker Guide', url: 'https://dressmakerguide.com' },
    },
  ],
  sources: [
    ['Dressmaker on Steam (fabrics, accessories, assembly)', LINKS.steam],
    ['Official itch.io devlog', LINKS.itchDevlog],
  ],
  body: BODY,
};
