import { resolveFigures } from '../data/images.mjs';
import { LINKS } from '../data/site.mjs';

const BODY = [
  "> Short answer: This wiki is the reference layer for the [dressmaker game](/) — fabric families, the pattern pieces a dress is built from, the four decoration types, the six-stage making loop and a plain-English glossary. Numbers the developers have not published are marked unpublished, not guessed.",
  "",
  "## How to use this wiki",
  "",
  "What this page covers, and what it does not.",
  "",
  "::: cards",
  "### What is documented",
  "Fabric families, pattern pieces, decoration types, the order of the making loop and the vocabulary. Every line traces to an official source.",
  "### What is not documented",
  "Per-bolt stats, prices, unlock order and the full attribute list. If a number is missing here, the developers have not published it.",
  "### How to correct it",
  "Found something wrong or out of date? [Tell us](/contact) with the page and the source. Corrections come from official material only.",
  ":::",
  "",
  "## Fabric families at a glance",
  "",
  "The store page names five fabrics — cotton, linen, wool, silk and velvet — inside a launch range of **over 450**. No per-bolt stats are published, so this table describes behaviour instead.",
  "",
  "| Fabric | What it does well | Best suited to | Watch out for |",
  "| --- | --- | --- | --- |",
  "| **Cotton** | Soft drape, matte finish, holds a shape | Everyday commissions, fitted bodices | Creases; flat beside silk; hides buttons |",
  "| **Linen** | Cool, dry handle, visible weave | Summer dresses, relaxed skirts | The loud weave swallows fine lace; creases |",
  "| **Wool** | Warm, matte, structured | Cold weather, tailored bodices | Bulk at seams and hems; swallows light trims |",
  "| **Silk** | High shine, fluid drape, near-weightless | Evening and wedding commissions | Off-centre panels show in the light; slippery |",
  "| **Velvet** | Deep colour, light-absorbing pile | One statement piece, such as a bodice | Pile runs a direction; opposing panels read differently |",
  "| **Specialty and printed** | Everything else on the shelf | Prints and print-led dresses | No per-bolt stats or unlock order published |",
  "",
  "> Tip: the last row is a family, not a bolt. We can tell you how cotton behaves, not that bolt 217 runs heavy.",
  "",
  "![Fabric shop shelves stacked with cloth bolts beside a list of fabrics and prices](@SHOT_fabric@ Bolt by bolt: prints, prices and the limits of the commission you are dressing for.)",
  "",
  "## Pattern pieces and garment panels",
  "",
  "A dress is assembled from pattern pieces you arrange, cut and sew: 'how you choose to arrange and cut out your fabric is what appears on the final dress.'",
  "",
  "> Tip: **grain** is the direction the threads run; align a piece with it and the panel hangs straight. **Bias** cuts diagonally across it for a softer drape.",
  "",
  "![Paper pattern pieces laid out on strawberry-print fabric with shears resting on the cloth](@SHOT_cut@ Pattern pieces laid on the cloth decide what the dress will look like. Then the shears decide it permanently.)",
  "",
  "| Garment area | What it decides | What to consider |",
  "| --- | --- | --- |",
  "| **Bodice** | The panel closest to the customer's face, and the busiest | Fine prints survive; align the centre front to the grain |",
  "| **Sleeves** | A mirrored pair, cut twice as opposites | Directional prints flip on the second sleeve |",
  "| **Skirt** | The largest pieces, so the most cloth and print on show | The home for a statement fabric; bias is dramatic |",
  "| **Trim and finishing** | Bands, edgings and decoration on the finished garment | Judge a trim against its panel — lace over velvet disappears |",
  "",
  "The [how to play Dressmaker](/how-to-play) walkthrough takes these stages in order; [sewing tips](/sewing-tips) goes deeper on layout and seam order.",
  "",
  "## Decoration types",
  "",
  "Four types — **buttons, bows, appliqué and lace trims** — placed 'wherever you like with complete creative freedom', from **over 350 accessories**. Appliqué is planned in the sketchbook, so it is a design choice too.",
  "",
  "| Decoration | What it is for | Where it reads best |",
  "| --- | --- | --- |",
  "| **Buttons** | Small, repeated, precise — a row is rhythm | Centre fronts, cuffs and bodice openings |",
  "| **Bows** | One soft shape that pulls the eye to a point | Waistlines, shoulders, the back, a neckline |",
  "| **Appliqué** | Shaped fabric placed on the surface | Motifs on a skirt, or across a bodice |",
  "| **Lace trim** | Edging for borders, hems and seams | Any line worth following: a hem, a cuff, a panel edge |",
  "",
  "![A finished strawberry-print dress on a mannequin beside a tray of accessories](@SHOT_decorate@ Sewing finished, decorating not: buttons, bows and lace can still be added before you hand it over.)",
  "",
  "## The making loop, in reference form",
  "",
  "Six stages, in the order the game asks for them. Dressmaker runs on two currencies, **coin and reputation**.",
  "",
  "| Stage | What you do | What it costs |",
  "| --- | --- | --- |",
  "| **1. Design in the sketchbook** | Choose silhouette, colour, samples and appliqué | Time only — designing is planning, not spending |",
  "| **2. Buy fabric** | Buy from the shelves; **over 450 fabrics** ship | Coin; per-fabric prices are not published |",
  "| **3. Arrange and cut** | Lay the pieces out, check the mannequin, then cut | The cloth. Irreversible; the preview is the only undo. |",
  "| **4. Sew the panels** | Feed the fabric through the sewing machine | Nothing — the machine has an infinite bobbin |",
  "| **5. Decorate** | Add buttons, bows, appliqué, lace and accessories | Not published; we will not guess |",
  "| **6. Hand in, or sell off the rack** | Turn the dress in, or sell pre-made dresses | Nothing up front — coin and reputation come back here |",
  "",
  "Handing in earns coin and reputation. What reputation unlocks, and in what order, has not been published. The [customer preferences](/customers) page covers reading the brief.",
  "",
  "![Fabric being fed through a sewing machine with the stitch prompts shown on screen](@SHOT_sew@ Panels go through the machine one seam at a time, with the controls on screen as you go.)",
  "",
  "## Key terms",
  "",
  "The words the game uses in its interface, in plain English.",
  "",
  "| Term | Plain-English meaning |",
  "| --- | --- |",
  "| **Grain** | The direction the threads run in a woven fabric; the predictable cut. |",
  "| **Bias** | Cutting diagonally across the grain, for a softer drape. |",
  "| **Panel** | One piece of a garment — bodice, sleeve, skirt, trim. You choose its fabric. |",
  "| **Appliqué** | Shaped fabric stitched onto another as a design. |",
  "| **Off the rack** | Ready-made rather than made to measure. |",
  "| **Mannequin** | The display figure that previews a garment before you cut. |",
  "| **Notions** | Small sewing supplies: buttons, trims, thread. |",
  "",
  "## What this wiki is, and what it is not",
  "",
  "This is a **fan-made reference**, not an official one. Every claim traces back to the official [Steam store page](@LINK_steam@) or the developers' own [itch.io devlog](@LINK_devlog@).",
  "",
  "> Note: in-game numbers are not published. Prices, unlock order, per-fabric stats and accessory costs have never been released, so any wiki quoting an exact coin price is guessing.",
  "",
  "Something wrong or out of date? [Tell us](/contact). To start playing instead, read [how to play Dressmaker](/how-to-play), then the [sewing tips](/sewing-tips) and [system requirements](/system-requirements).",
].join("\n")
  .split('\n').map((line) => resolveFigures(line)).join('\n')
  .replaceAll('@LINK_steam@', LINKS.steam)
  .replaceAll('@LINK_devlog@', LINKS.itchDevlog);

export const page = {
  url: '/wiki',
  title: 'Dressmaker Wiki: Fabrics, Patterns & Accessories',
  description: 'A fan-made Dressmaker wiki built from the official store page and devlog: fabric families, pattern pieces, decorations, the making loop and a glossary.',
  h1: 'Dressmaker Wiki',
  eyebrow: "Reference",
  lede: "This is the reference layer for the dressmaker game — the tables to keep open in a second tab. Dressmaker is a cozy dressmaking simulation from elyaradine, sarandipityx and raithza, published by Free Lives and out on Steam since September 21, 2026 for Windows and macOS.",
  facts: [
    ['Fabric families', "Cotton, linen, wool, silk, velvet"],
    ['Launch content', "450+ fabrics, 150+ dress pieces"],
    ['Accessories', "350+ across buttons, bows, appliqué, lace"],
    ['Assembly', "Pattern pieces arranged on cloth by hand"],
    ['Decoration', "Placed freely after sewing"],
    ['Not published', "Per-bolt stats, prices, unlock order"],
  ],
  updated: '2026-09-21',
  updatedHuman: 'September 21, 2026',
  ogType: 'article',
  crumbs: [{ name: 'Home', url: '/' }, { name: 'Wiki', url: '/wiki' }],
  schema: [
    {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Dressmaker Wiki: Fabrics, Patterns & Accessories',
      description: 'Reference tables for Dressmaker: fabric families, pattern pieces and panels, decoration types, the six-stage making loop and a glossary of dressmaking terms.',
      datePublished: '2026-09-21',
      dateModified: '2026-09-21',
      inLanguage: 'en-US',
      author: { '@type': 'Organization', name: 'Dressmaker Guide' },
      about: {
        '@type': 'VideoGame',
        name: 'Dressmaker',
        url: LINKS.steam,
        genre: ['Simulation', 'Casual', 'Indie'],
        gamePlatform: ['PC (Microsoft Windows)', 'macOS'],
        datePublished: '2026-09-21',
      },
      isPartOf: { '@type': 'WebSite', name: 'Dressmaker Guide', url: 'https://dressmakerguide.com' },
    },
  ],
  sources: [
    ['Dressmaker on Steam (fabrics, accessories, assembly)', LINKS.steam],
    ['Official itch.io devlog', LINKS.itchDevlog],
  ],
  body: BODY,
};
